/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * TNT.WebApi 接口文档 | Demo 模块 - version v10.0.1.0
 *
 * TNT.WebApi 项目接口文档, Powered By .NET 10.0.1
 *
 * OpenAPI version: 3.1.1
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'sse.sse1': ['GET', '/api/Demo/Sse/sse1'],
  'sse.sse2': ['GET', '/api/Demo/Sse/sse2'],
  'subscribeMessage.sendSubscribeMessageTo': ['GET', '/api/Demo/SubscribeMessage/sendSubscribeMessageTo'],
  'subscribeMessage.sendSubscribeEmployeeMessageTo': [
    'GET',
    '/api/Demo/SubscribeMessage/sendSubscribeEmployeeMessageTo'
  ]
};
