/* eslint-disable */
/* biome-ignore-all */
/* stylelint-disable */
/* editorconfig-checker-disable-file */
/* oxlint-disable */
/* oxcformat-ignore */
/**
 * TNT.WebApi 接口文档 | Demo 模块 - version v10.0.9.0
 *
 * TNT.WebApi 项目接口文档, Powered By .NET 10.0.12
 *
 * OpenAPI version: 3.1.1
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://worma.js.org
 *
 * **Do not edit the file manually.**
 */
/// <reference types='./globals.d.ts' />

const apiDefinitions = {
  'seal.createSeal': ['POST', '/api/Demo/Seal/create'],
  'seal.toUri': ['GET', '/api/Demo/Seal/datauri'],
  'sse.sse1': ['GET', '/api/Demo/Sse/sse1'],
  'sse.sse2': ['GET', '/api/Demo/Sse/sse2'],
  'subscribeMessage.sendSubscribeMessageTo': ['GET', '/api/Demo/SubscribeMessage/sendSubscribeMessageTo'],
  'subscribeMessage.sendSubscribeEmployeeMessageTo': [
    'GET',
    '/api/Demo/SubscribeMessage/sendSubscribeEmployeeMessageTo'
  ]
} as const;

export default apiDefinitions;
