/* eslint-disable */
/* biome-ignore-all */
/* stylelint-disable */
/* editorconfig-checker-disable-file */
/* oxlint-disable */
/* oxcformat-ignore */
/**
 * TNT.WebApi 接口文档 | Demo 模块 - version v10.0.9.0
 *
 * TNT.WebApi 项目接口文档, Powered By .NET 10.0.12
 *
 * OpenAPI version: 3.1.1
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://worma.js.org
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { alovaInstance, $$userConfigMap } from './index';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;

type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export interface ApiResultOfboolean {
  /**
   * 响应编号
   */

  code?: number | string;
  /**
   * 响应消息
   */

  message?: string;
  /**
   * 响应数据 T
   */

  data?: boolean;
  /**
   * 扩展数据
   */

  extend?: null;
  /**
   * 请求是否返回正确
   */

  isSuccess?: boolean;
}
export interface BusinessLicenseDTO {
  businessName: string;
  licenseCode: string;
  copyNumber?: string;
  licenseType: string;
  legalRepresentative: string;
  registeredCapital: string;
  createdDate: string;
  registeredAddress: string;
  businessScope: string;
  issuingAuthority: string;
  issueDate: string;
}

declare global {
  interface Webapi_Demo {
    seal: {
      /**
       * ---
       *
       * [POST] 创建企业营业执照信息，并生成对应的营业执照图片
       *
       * **path:** /api/Demo/Seal/create
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   businessName: string
       *   licenseCode: string
       *   copyNumber?: string
       *   licenseType: string
       *   legalRepresentative: string
       *   registeredCapital: string
       *   createdDate: string
       *   registeredAddress: string
       *   businessScope: string
       *   issuingAuthority: string
       *   issueDate: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      createSeal<
        Config extends Alova2MethodConfig<null> & {
          data: BusinessLicenseDTO;
        }
      >(
        config: Config
      ): Alova2Method<null, 'seal.createSeal', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/Demo/Seal/datauri
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   top?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      toUri<
        Config extends Alova2MethodConfig<null> & {
          params: {
            top?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<null, 'seal.toUri', Config>;
    };
    sse: {
      /**
       * ---
       *
       * [GET] sse 流式接口示例
       *
       * **path:** /api/Demo/Sse/sse1
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      sse1<Config extends Alova2MethodConfig<null>>(config?: Config): Alova2Method<null, 'sse.sse1', Config>;
      /**
       * ---
       *
       * [GET] .net 10 SSE 示例
       *
       * **path:** /api/Demo/Sse/sse2
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      sse2<Config extends Alova2MethodConfig<null>>(config?: Config): Alova2Method<null, 'sse.sse2', Config>;
    };
    subscribeMessage: {
      /**
       * ---
       *
       * [GET] 发送订阅模板消息给指定用户
       *
       * **path:** /api/Demo/SubscribeMessage/sendSubscribeMessageTo
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   openId?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number | string
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: boolean
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      sendSubscribeMessageTo<
        Config extends Alova2MethodConfig<ApiResultOfboolean> & {
          params: {
            openId?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfboolean, 'subscribeMessage.sendSubscribeMessageTo', Config>;
      /**
       * ---
       *
       * [GET] 发送用工关系订阅模板消息给指定用户
       *
       * **path:** /api/Demo/SubscribeMessage/sendSubscribeEmployeeMessageTo
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   openId?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number | string
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: boolean
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      sendSubscribeEmployeeMessageTo<
        Config extends Alova2MethodConfig<ApiResultOfboolean> & {
          params: {
            openId?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfboolean, 'subscribeMessage.sendSubscribeEmployeeMessageTo', Config>;
    };
  }

  var Webapi_Demo: Webapi_Demo;
}

export {};
