/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * TNT.WebApi 接口文档 | 基础模块 - version v9.0.11.0
 *
 * TNT.WebApi 项目接口文档, Powered By .NET 9.0.11
 *
 * OpenAPI version: 3.0.1
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'articleAgreeLog.countArticleAgreeLog': ['GET', '/api/Base/ArticleAgreeLogs/count'],
  'articleAgreeLog.setArticleAgreeLog': ['POST', '/api/Base/ArticleAgreeLogs/set'],
  'articleCategory.getArticleCategoryList': ['GET', '/api/Base/ArticleCategories/list'],
  'articleCategory.nodeListArticleCategory': ['GET', '/api/Base/ArticleCategories/nodeList'],
  'articleCategory.getArticleCategory': ['GET', '/api/Base/ArticleCategories/get'],
  'articleCategory.createArticleCategory': ['POST', '/api/Base/ArticleCategories/create'],
  'articleCategory.updateArticleCategory': ['PUT', '/api/Base/ArticleCategories/update'],
  'articleCategory.deleteArticleCategory': ['DELETE', '/api/Base/ArticleCategories/delete'],
  'articleCategory.deleteArticleCategories': ['DELETE', '/api/Base/ArticleCategories/deletes'],
  'article.getArticleList': ['GET', '/api/Base/Articles/list'],
  'article.getArticle': ['GET', '/api/Base/Articles/get'],
  'article.createArticle': ['POST', '/api/Base/Articles/create'],
  'article.updateArticle': ['PUT', '/api/Base/Articles/update'],
  'article.deleteArticle': ['DELETE', '/api/Base/Articles/delete'],
  'article.deleteArticles': ['DELETE', '/api/Base/Articles/deletes'],
  'article.publishArticleToDraft': ['POST', '/api/Base/Articles/publishToDraft'],
  'auth.login': ['POST', '/api/Base/Auth/login'],
  'auth.easyLogin': ['POST', '/api/Base/Auth/easyLogin'],
  'auth.getProfileInfoByToken': ['GET', '/api/Base/Auth/getProfileInfoByToken'],
  'auth.getProfileInfo': ['GET', '/api/Base/Auth/getProfileInfo'],
  'auth.logout': ['POST', '/api/Base/Auth/logout'],
  'auth.sendEmail': ['POST', '/api/Base/Auth/sendEmail'],
  'carousel.getCarouselList': ['GET', '/api/Base/Carousels/list'],
  'carousel.getCarousel': ['GET', '/api/Base/Carousels/get'],
  'carousel.getCarouselByKey': ['GET', '/api/Base/Carousels/getByKey'],
  'carousel.createCarousel': ['POST', '/api/Base/Carousels/create'],
  'carousel.updateCarousel': ['PUT', '/api/Base/Carousels/update'],
  'carousel.deleteCarousel': ['DELETE', '/api/Base/Carousels/delete'],
  'dynamicMenu.getDynamicMenuList': ['GET', '/api/Base/DynamicMenus/list'],
  'dynamicMenu.getDynamicMenu': ['GET', '/api/Base/DynamicMenus/get'],
  'dynamicMenu.createDynamicMenu': ['POST', '/api/Base/DynamicMenus/create'],
  'dynamicMenu.updateDynamicMenu': ['PUT', '/api/Base/DynamicMenus/update'],
  'dynamicMenu.deleteDynamicMenu': ['DELETE', '/api/Base/DynamicMenus/delete'],
  'image.getRemoteImage': ['GET', '/api/Base/Images/getRemote'],
  'lbs.geocoderByLocation': ['GET', '/api/Base/Lbs/Geocoder/byLocation'],
  'lbs.geocoderGetLocation': ['GET', '/api/Base/Lbs/Geocoder/getLocation'],
  'qrcode.getQrcode': ['GET', '/api/Base/Qrcode/get'],
  'role.getRoleList': ['GET', '/api/Base/Roles/list'],
  'role.getRole': ['GET', '/api/Base/Roles/get'],
  'role.getRoleByName': ['GET', '/api/Base/Roles/getByName'],
  'role.createRole': ['POST', '/api/Base/Roles/create'],
  'role.updateRole': ['PUT', '/api/Base/Roles/update'],
  'role.deleteRole': ['DELETE', '/api/Base/Roles/delete'],
  'role.deleteRoleByName': ['DELETE', '/api/Base/Roles/deleteByName'],
  'role.syncRoleRightsToUsers': ['POST', '/api/Base/Roles/syncRightsToUsers'],
  'upFile.upload': ['POST', '/api/Base/UpFiles/upload'],
  'userOperateLog.getUserOperateLogList': ['GET', '/api/Base/UserOperateLogs/list'],
  'userOperateLog.getUserOperateLog': ['GET', '/api/Base/UserOperateLogs/get'],
  'userOperateLog.createUserOperateLog': ['POST', '/api/Base/UserOperateLogs/create'],
  'userOperateLog.updateUserOperateLog': ['PUT', '/api/Base/UserOperateLogs/update'],
  'userOperateLog.deleteUserOperateLog': ['DELETE', '/api/Base/UserOperateLogs/delete'],
  'userOperateLog.clearUserOperateLog': ['DELETE', '/api/Base/UserOperateLogs/clear'],
  'user.getUserList': ['GET', '/api/Base/Users/list'],
  'user.getUser': ['GET', '/api/Base/Users/get'],
  'user.getUserByName': ['GET', '/api/Base/Users/getByName'],
  'user.getUserPermission': ['GET', '/api/Base/Users/getPermission'],
  'user.getUserMenu': ['GET', '/api/Base/Users/getUserMenu'],
  'user.getUserMenuTree': ['GET', '/api/Base/Users/getUserMenuTree'],
  'user.getUserAllPages': ['GET', '/api/Base/Users/getAllPages'],
  'user.createUser': ['POST', '/api/Base/Users/create'],
  'user.updateUser': ['PUT', '/api/Base/Users/update'],
  'user.getUserRoles': ['GET', '/api/Base/Users/getRoles'],
  'user.setUserRoles': ['POST', '/api/Base/Users/setRoles'],
  'user.changeUserPassword': ['POST', '/api/Base/Users/changePassword'],
  'user.resetUserPassword': ['POST', '/api/Base/Users/resetPassword'],
  'user.deleteUser': ['DELETE', '/api/Base/Users/delete'],
  'user.deleteUserByName': ['DELETE', '/api/Base/Users/deleteByName'],
  'user.deleteUsers': ['POST', '/api/Base/Users/deletes']
};
