/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 后羿 接口文档 | 基础模块 - version v9.0.9.0
 *
 * 后羿 项目接口文档, Powered By .NET 9.0.10
 *
 * OpenAPI version: 3.0.1
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'articleAgreeLog.CountArticleAgreeLogs': ['GET', '/api/Base/ArticleAgreeLogs/count'],
  'articleAgreeLog.SetArticleAgreeLog': ['POST', '/api/Base/ArticleAgreeLogs/set'],
  'articleCategory.GetArticleCategoryList': ['GET', '/api/Base/ArticleCategories/list'],
  'articleCategory.GetArticleCategoryNodeList': ['GET', '/api/Base/ArticleCategories/nodeList'],
  'articleCategory.GetArticleCategory': ['GET', '/api/Base/ArticleCategories/get'],
  'articleCategory.CreateArticleCategory': ['POST', '/api/Base/ArticleCategories/create'],
  'articleCategory.UpdateArticleCategory': ['PUT', '/api/Base/ArticleCategories/update'],
  'articleCategory.DeleteArticleCategory': ['DELETE', '/api/Base/ArticleCategories/delete'],
  'articleCategory.DeleteArticleCategories': ['DELETE', '/api/Base/ArticleCategories/deletes'],
  'article.GetArticleList': ['GET', '/api/Base/Articles/list'],
  'article.GetArticle': ['GET', '/api/Base/Articles/get'],
  'article.CreateArticle': ['POST', '/api/Base/Articles/create'],
  'article.UpdateArticle': ['PUT', '/api/Base/Articles/update'],
  'article.DeleteArticle': ['DELETE', '/api/Base/Articles/delete'],
  'article.DeleteArticles': ['DELETE', '/api/Base/Articles/deletes'],
  'article.post_api_base_articles_publish_to_draft': ['POST', '/api/Base/Articles/publishToDraft'],
  'auth.Login': ['POST', '/api/Base/Auth/login'],
  'auth.EasyLogin': ['POST', '/api/Base/Auth/easyLogin'],
  'auth.GetProfileInfoByToken': ['GET', '/api/Base/Auth/getProfileInfoByToken'],
  'auth.GetProfileInfo': ['GET', '/api/Base/Auth/getProfileInfo'],
  'auth.Logout': ['POST', '/api/Base/Auth/logout'],
  'auth.SendEmailValidateCode': ['POST', '/api/Base/Auth/sendEmailValidateCode'],
  'auth.Register': ['POST', '/api/Base/Auth/register'],
  'carousel.GetCarouselList': ['GET', '/api/Base/Carousels/list'],
  'carousel.GetCarousel': ['GET', '/api/Base/Carousels/get'],
  'carousel.GetCarouselByKey': ['GET', '/api/Base/Carousels/getByKey'],
  'carousel.CreateCarousel': ['POST', '/api/Base/Carousels/create'],
  'carousel.UpdateCarousel': ['PUT', '/api/Base/Carousels/update'],
  'carousel.DeleteCarousel': ['DELETE', '/api/Base/Carousels/delete'],
  'carousel.DeleteCarousels': ['DELETE', '/api/Base/Carousels/deletes'],
  'dynamicMenu.GetDynamicMenuList': ['GET', '/api/Base/DynamicMenus/list'],
  'dynamicMenu.GetDynamicMenu': ['GET', '/api/Base/DynamicMenus/get'],
  'dynamicMenu.CreateDynamicMenu': ['POST', '/api/Base/DynamicMenus/create'],
  'dynamicMenu.UpdateDynamicMenu': ['PUT', '/api/Base/DynamicMenus/update'],
  'dynamicMenu.DeleteDynamicMenu': ['DELETE', '/api/Base/DynamicMenus/delete'],
  'dynamicMenu.DeleteDynamicMenus': ['DELETE', '/api/Base/DynamicMenus/deletes'],
  'imageBridge.GetRemoteImage': ['GET', '/api/Base/ImageBridge/getRemote'],
  'lbs.GetGeocoderByLocation': ['GET', '/api/Base/Lbs/Geocoder/byLocation'],
  'lbs.GetGeocoderLocation': ['GET', '/api/Base/Lbs/Geocoder/getLocation'],
  'qrcode.GetQrcode': ['GET', '/api/Base/Qrcode/get'],
  'role.GetRolesList': ['GET', '/api/Base/Roles/list'],
  'role.GetRole': ['GET', '/api/Base/Roles/get'],
  'role.GetRoleByName': ['GET', '/api/Base/Roles/getByName'],
  'role.CreateRole': ['POST', '/api/Base/Roles/create'],
  'role.UpdateRole': ['PUT', '/api/Base/Roles/update'],
  'role.DeleteRole': ['DELETE', '/api/Base/Roles/delete'],
  'role.DeleteRoleByName': ['DELETE', '/api/Base/Roles/deleteByName'],
  'role.SyncRightsToUsers': ['POST', '/api/Base/Roles/syncRightsToUsers'],
  'upFile.upload': ['POST', '/api/Base/UpFiles/upload'],
  'userOperateLog.GetUserOperateLogList': ['GET', '/api/Base/UserOperateLogs/list'],
  'userOperateLog.GetUserOperateLog': ['GET', '/api/Base/UserOperateLogs/get'],
  'userOperateLog.CreateUserOperateLog': ['POST', '/api/Base/UserOperateLogs/create'],
  'userOperateLog.UpdateUserOperateLog': ['PUT', '/api/Base/UserOperateLogs/update'],
  'userOperateLog.DeleteUserOperateLog': ['DELETE', '/api/Base/UserOperateLogs/delete'],
  'userOperateLog.ClearUserOperateLogs': ['DELETE', '/api/Base/UserOperateLogs/clear'],
  'user.GetUserList': ['GET', '/api/Base/Users/list'],
  'user.GetUser': ['GET', '/api/Base/Users/get'],
  'user.GetUserByName': ['GET', '/api/Base/Users/getByName'],
  'user.GetUserPermission': ['GET', '/api/Base/Users/getPermission'],
  'user.CreateUser': ['POST', '/api/Base/Users/create'],
  'user.CreateUserByParent': ['POST', '/api/Base/Users/createByParent'],
  'user.UpdateUserProfile': ['PUT', '/api/Base/Users/update'],
  'user.GetUserRoles': ['GET', '/api/Base/Users/getRoles'],
  'user.SetUserRoles': ['POST', '/api/Base/Users/setRoles'],
  'user.ChangeUserPassword': ['POST', '/api/Base/Users/changePassword'],
  'user.ResetUserPassword': ['POST', '/api/Base/Users/resetPassword'],
  'user.DeleteUser': ['DELETE', '/api/Base/Users/delete'],
  'user.DeleteUserByName': ['DELETE', '/api/Base/Users/deleteByName'],
  'user.DeleteUsers': ['POST', '/api/Base/Users/deletes']
};
