/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 后羿 接口文档 | 基础模块 - version v9.0.9.0
 *
 * 后羿 项目接口文档, Powered By .NET 9.0.10
 *
 * OpenAPI version: 3.0.1
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'general.get_api_base_article_agree_logs_count': ['GET', '/api/Base/ArticleAgreeLogs/count'],
  'general.post_api_base_article_agree_logs_set': ['POST', '/api/Base/ArticleAgreeLogs/set'],
  'general.get_api_base_article_categories_list': ['GET', '/api/Base/ArticleCategories/list'],
  'general.get_api_base_article_categories_node_list': ['GET', '/api/Base/ArticleCategories/nodeList'],
  'general.get_api_base_article_categories_get': ['GET', '/api/Base/ArticleCategories/get'],
  'general.post_api_base_article_categories_create': ['POST', '/api/Base/ArticleCategories/create'],
  'general.put_api_base_article_categories_update': ['PUT', '/api/Base/ArticleCategories/update'],
  'general.delete_api_base_article_categories_delete': ['DELETE', '/api/Base/ArticleCategories/delete'],
  'general.delete_api_base_article_categories_deletes': ['DELETE', '/api/Base/ArticleCategories/deletes'],
  'general.get_api_base_articles_list': ['GET', '/api/Base/Articles/list'],
  'general.get_api_base_articles_get': ['GET', '/api/Base/Articles/get'],
  'general.post_api_base_articles_create': ['POST', '/api/Base/Articles/create'],
  'general.put_api_base_articles_update': ['PUT', '/api/Base/Articles/update'],
  'general.delete_api_base_articles_delete': ['DELETE', '/api/Base/Articles/delete'],
  'general.delete_api_base_articles_deletes': ['DELETE', '/api/Base/Articles/deletes'],
  'general.post_api_base_articles_publish_to_draft': ['POST', '/api/Base/Articles/publishToDraft'],
  'general.post_api_base_auth_login': ['POST', '/api/Base/Auth/login'],
  'general.post_api_base_auth_easy_login': ['POST', '/api/Base/Auth/easyLogin'],
  'general.get_api_base_auth_get_profile_info_by_token': ['GET', '/api/Base/Auth/getProfileInfoByToken'],
  'general.get_api_base_auth_get_profile_info': ['GET', '/api/Base/Auth/getProfileInfo'],
  'general.post_api_base_auth_logout': ['POST', '/api/Base/Auth/logout'],
  'general.post_api_base_auth_send_email_validate_code': ['POST', '/api/Base/Auth/sendEmailValidateCode'],
  'general.post_api_base_auth_register': ['POST', '/api/Base/Auth/register'],
  'general.get_api_base_carousels_list': ['GET', '/api/Base/Carousels/list'],
  'general.get_api_base_carousels_get': ['GET', '/api/Base/Carousels/get'],
  'general.get_api_base_carousels_get_by_key': ['GET', '/api/Base/Carousels/getByKey'],
  'general.post_api_base_carousels_create': ['POST', '/api/Base/Carousels/create'],
  'general.put_api_base_carousels_update': ['PUT', '/api/Base/Carousels/update'],
  'general.delete_api_base_carousels_delete': ['DELETE', '/api/Base/Carousels/delete'],
  'general.get_api_base_dynamic_menus_list': ['GET', '/api/Base/DynamicMenus/list'],
  'general.get_api_base_dynamic_menus_get': ['GET', '/api/Base/DynamicMenus/get'],
  'general.post_api_base_dynamic_menus_create': ['POST', '/api/Base/DynamicMenus/create'],
  'general.put_api_base_dynamic_menus_update': ['PUT', '/api/Base/DynamicMenus/update'],
  'general.delete_api_base_dynamic_menus_delete': ['DELETE', '/api/Base/DynamicMenus/delete'],
  'general.get_api_base_image_bridge_get_remote': ['GET', '/api/Base/ImageBridge/getRemote'],
  'general.get_api_base_lbs_geocoder_by_location': ['GET', '/api/Base/Lbs/Geocoder/byLocation'],
  'general.get_api_base_lbs_geocoder_get_location': ['GET', '/api/Base/Lbs/Geocoder/getLocation'],
  'general.get_api_base_qrcode_get': ['GET', '/api/Base/Qrcode/get'],
  'general.get_api_base_qrcode_generate': ['GET', '/api/Base/Qrcode/generate'],
  'general.get_api_base_roles_list': ['GET', '/api/Base/Roles/list'],
  'general.get_api_base_roles_get': ['GET', '/api/Base/Roles/get'],
  'general.get_api_base_roles_get_by_name': ['GET', '/api/Base/Roles/getByName'],
  'general.post_api_base_roles_create': ['POST', '/api/Base/Roles/create'],
  'general.put_api_base_roles_update': ['PUT', '/api/Base/Roles/update'],
  'general.delete_api_base_roles_delete': ['DELETE', '/api/Base/Roles/delete'],
  'general.delete_api_base_roles_delete_by_name': ['DELETE', '/api/Base/Roles/deleteByName'],
  'general.post_api_base_roles_sync_rights_to_users': ['POST', '/api/Base/Roles/syncRightsToUsers'],
  'general.post_api_base_up_files_upload': ['POST', '/api/Base/UpFiles/upload'],
  'general.get_api_base_user_operate_logs_list': ['GET', '/api/Base/UserOperateLogs/list'],
  'general.get_api_base_user_operate_logs_get': ['GET', '/api/Base/UserOperateLogs/get'],
  'general.post_api_base_user_operate_logs_create': ['POST', '/api/Base/UserOperateLogs/create'],
  'general.put_api_base_user_operate_logs_update': ['PUT', '/api/Base/UserOperateLogs/update'],
  'general.delete_api_base_user_operate_logs_delete': ['DELETE', '/api/Base/UserOperateLogs/delete'],
  'general.delete_api_base_user_operate_logs_clear': ['DELETE', '/api/Base/UserOperateLogs/clear'],
  'general.get_api_base_users_list': ['GET', '/api/Base/Users/list'],
  'general.get_api_base_users_get': ['GET', '/api/Base/Users/get'],
  'general.get_api_base_users_get_by_name': ['GET', '/api/Base/Users/getByName'],
  'general.get_api_base_users_get_permission': ['GET', '/api/Base/Users/getPermission'],
  'general.post_api_base_users_create': ['POST', '/api/Base/Users/create'],
  'general.post_api_base_users_create_by_parent': ['POST', '/api/Base/Users/createByParent'],
  'general.put_api_base_users_update': ['PUT', '/api/Base/Users/update'],
  'general.get_api_base_users_get_roles': ['GET', '/api/Base/Users/getRoles'],
  'general.post_api_base_users_set_roles': ['POST', '/api/Base/Users/setRoles'],
  'general.post_api_base_users_change_password': ['POST', '/api/Base/Users/changePassword'],
  'general.post_api_base_users_reset_password': ['POST', '/api/Base/Users/resetPassword'],
  'general.delete_api_base_users_delete': ['DELETE', '/api/Base/Users/delete'],
  'general.delete_api_base_users_delete_by_name': ['DELETE', '/api/Base/Users/deleteByName'],
  'general.post_api_base_users_deletes': ['POST', '/api/Base/Users/deletes']
};
