/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 后羿 接口文档 | 业务模块 - version v9.0.9.0
 *
 * 后羿 项目接口文档, Powered By .NET 9.0.10
 *
 * OpenAPI version: 3.0.1
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'general.get_api_business_trading_channels_list': ['GET', '/api/Business/TradingChannels/list'],
  'general.get_api_business_trading_channels_get': ['GET', '/api/Business/TradingChannels/get'],
  'general.post_api_business_trading_channels_create': ['POST', '/api/Business/TradingChannels/create'],
  'general.put_api_business_trading_channels_update': ['PUT', '/api/Business/TradingChannels/update'],
  'general.delete_api_business_trading_channels_delete': ['DELETE', '/api/Business/TradingChannels/delete'],
  'general.post_api_business_trading_channels_deletes': ['POST', '/api/Business/TradingChannels/deletes'],
  'general.get_api_business_user_asset_logs_list': ['GET', '/api/Business/UserAssetLogs/list'],
  'general.get_api_business_user_asset_logs_get': ['GET', '/api/Business/UserAssetLogs/get'],
  'general.get_api_business_user_orders_list': ['GET', '/api/Business/UserOrders/list'],
  'general.get_api_business_user_orders_get': ['GET', '/api/Business/UserOrders/get'],
  'general.post_api_business_user_orders_create': ['POST', '/api/Business/UserOrders/create'],
  'general.put_api_business_user_orders_completed': ['PUT', '/api/Business/UserOrders/completed'],
  'general.delete_api_business_user_orders_delete': ['DELETE', '/api/Business/UserOrders/delete'],
  'general.post_api_business_user_orders_deletes': ['POST', '/api/Business/UserOrders/deletes'],
  'general.get_api_business_user_team_maps_list': ['GET', '/api/Business/UserTeamMaps/list'],
  'general.get_api_business_user_team_maps_get': ['GET', '/api/Business/UserTeamMaps/get'],
  'general.post_api_business_user_team_maps_create': ['POST', '/api/Business/UserTeamMaps/create'],
  'general.post_api_business_user_team_maps_transfer_usdt': ['POST', '/api/Business/UserTeamMaps/transferUsdt'],
  'general.put_api_business_user_team_maps_update': ['PUT', '/api/Business/UserTeamMaps/update'],
  'general.delete_api_business_user_team_maps_delete': ['DELETE', '/api/Business/UserTeamMaps/delete'],
  'general.post_api_business_user_team_maps_deletes': ['POST', '/api/Business/UserTeamMaps/deletes']
};
