/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 后羿 接口文档 | 业务模块 - version v9.0.9.0
 *
 * 后羿 项目接口文档, Powered By .NET 9.0.10
 *
 * OpenAPI version: 3.0.1
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'tradingChannel.GetTradingChannelList': ['GET', '/api/Business/TradingChannels/list'],
  'tradingChannel.GetTradingChannel': ['GET', '/api/Business/TradingChannels/get'],
  'tradingChannel.CreateTradingChannel': ['POST', '/api/Business/TradingChannels/create'],
  'tradingChannel.UpdateTradingChannel': ['PUT', '/api/Business/TradingChannels/update'],
  'tradingChannel.DeleteTradingChannel': ['DELETE', '/api/Business/TradingChannels/delete'],
  'tradingChannel.DeleteTradingChannels': ['POST', '/api/Business/TradingChannels/deletes'],
  'userAssetLog.GetUserAssetLogList': ['GET', '/api/Business/UserAssetLogs/list'],
  'userAssetLog.GetUserAssetLog': ['GET', '/api/Business/UserAssetLogs/get'],
  'userOrder.getUserOrders': ['GET', '/api/Business/UserOrders/list'],
  'userOrder.getUserOrder': ['GET', '/api/Business/UserOrders/get'],
  'userOrder.createUserOrder': ['POST', '/api/Business/UserOrders/create'],
  'userOrder.completedUserOrder': ['PUT', '/api/Business/UserOrders/completed'],
  'userOrder.deleteUserOrder': ['DELETE', '/api/Business/UserOrders/delete'],
  'userOrder.deleteUserOrders': ['POST', '/api/Business/UserOrders/deletes'],
  'userTeamMap.getUserTeamMapList': ['GET', '/api/Business/UserTeamMaps/list'],
  'userTeamMap.getUserTeamMap': ['GET', '/api/Business/UserTeamMaps/get'],
  'userTeamMap.createUserTeamMap': ['POST', '/api/Business/UserTeamMaps/create'],
  'userTeamMap.transferUsdt': ['POST', '/api/Business/UserTeamMaps/transferUsdt'],
  'userTeamMap.updateUserTeamMap': ['PUT', '/api/Business/UserTeamMaps/update'],
  'userTeamMap.deleteUserTeamMap': ['DELETE', '/api/Business/UserTeamMaps/delete'],
  'userTeamMap.deleteUserTeamMaps': ['POST', '/api/Business/UserTeamMaps/deletes']
};
