/* tslint:disable */
/* eslint-disable */
/**
 * 后羿 接口文档 | 业务模块 - version v9.0.9.0
 *
 * 后羿 项目接口文档, Powered By .NET 9.0.10
 *
 * OpenAPI version: 3.0.1
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from './index';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export interface TradingChannel {
  id?: string;
  name?: string;
  exchangeRate?: number;
  description?: string;
  createdAt?: string;
}
export type AssetTypeEnum = number;
export type OrderStatusEnum = number;
export type UserOrderConfigModel = {
  walletId?: string;
  channelId?: string;
  channelName?: string;
  channelRate?: number;
} | null;
export interface UserOrder {
  id?: string;
  userId?: string;
  userName?: string;
  assetType?: AssetTypeEnum;
  amount?: number;
  status?: OrderStatusEnum;
  time?: string;
  description?: string;
  config?: UserOrderConfigModel;
}
export interface UserTeamMap {
  id?: string;
  userId?: string;
  userName?: string;
  commissionRate?: number;
  usdtValue?: number;
  bondValue?: number;
  parentUserId?: string | null;
  parentUserName?: string | null;
  level?: number;
  ancestorPath?: string;
  descendantCount?: number;
  createdAt?: string;
}
export type PageListOfTradingChannel = {
  list?: TradingChannel[];
  page?: number;
  pageSize?: number;
  totalPageCount?: number;
  totalItemCount?: number;
  extendData?: null;
} | null;
export interface ApiResultOfPageListOfTradingChannel {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: PageListOfTradingChannel;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export type TradingChannel2 = {
  id?: string;
  name?: string;
  exchangeRate?: number;
  description?: string;
  createdAt?: string;
} | null;
export interface ApiResultOfTradingChannel {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: TradingChannel2;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export interface ApiResult {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: null;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export type AssetChangeType = number;
export interface UserAssetLog {
  id?: string;
  userId?: string;
  userName?: string;
  assetType?: AssetTypeEnum;
  changeType?: AssetChangeType;
  value?: number;
  balance?: number;
  description?: string;
  time?: string;
}
export type PageListOfUserAssetLog = {
  list?: UserAssetLog[];
  page?: number;
  pageSize?: number;
  totalPageCount?: number;
  totalItemCount?: number;
  extendData?: null;
} | null;
export interface ApiResultOfPageListOfUserAssetLog {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: PageListOfUserAssetLog;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export type UserAssetLog2 = {
  id?: string;
  userId?: string;
  userName?: string;
  assetType?: AssetTypeEnum;
  changeType?: AssetChangeType;
  value?: number;
  balance?: number;
  description?: string;
  time?: string;
} | null;
export interface ApiResultOfUserAssetLog {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: UserAssetLog2;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export type PageListOfUserOrder = {
  list?: UserOrder[];
  page?: number;
  pageSize?: number;
  totalPageCount?: number;
  totalItemCount?: number;
  extendData?: null;
} | null;
export interface ApiResultOfPageListOfUserOrder {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: PageListOfUserOrder;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export type UserOrder2 = {
  id?: string;
  userId?: string;
  userName?: string;
  assetType?: AssetTypeEnum;
  amount?: number;
  status?: OrderStatusEnum;
  time?: string;
  description?: string;
  config?: UserOrderConfigModel;
} | null;
export interface ApiResultOfUserOrder {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: UserOrder2;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export type PageListOfUserTeamMap = {
  list?: UserTeamMap[];
  page?: number;
  pageSize?: number;
  totalPageCount?: number;
  totalItemCount?: number;
  extendData?: null;
} | null;
export interface ApiResultOfPageListOfUserTeamMap {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: PageListOfUserTeamMap;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export type UserTeamMap2 = {
  id?: string;
  userId?: string;
  userName?: string;
  commissionRate?: number;
  usdtValue?: number;
  bondValue?: number;
  parentUserId?: string | null;
  parentUserName?: string | null;
  level?: number;
  ancestorPath?: string;
  descendantCount?: number;
  createdAt?: string;
} | null;
export interface ApiResultOfUserTeamMap {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: UserTeamMap2;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
declare global {
  interface Business {
    general: {
      /**
       * ---
       *
       * [GET] 获取交易渠道列表
       *
       * **path:** /api/Business/TradingChannels/list
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   keyword?: string
       *   page?: number
       *   pagesize?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     // [items] start
       *     // [items] end
       *     list?: Array<{
       *       id?: string
       *       name?: string
       *       exchangeRate?: number
       *       description?: string
       *       createdAt?: string
       *     }>
       *     page?: number
       *     pageSize?: number
       *     totalPageCount?: number
       *     totalItemCount?: number
       *     extendData?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_business_trading_channels_list<
        Config extends Alova2MethodConfig<ApiResultOfPageListOfTradingChannel> & {
          params: {
            keyword?: string;
            page?: number;
            pagesize?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfPageListOfTradingChannel, 'general.get_api_business_trading_channels_list', Config>;
      /**
       * ---
       *
       * [GET] 获取交易渠道详情
       *
       * **path:** /api/Business/TradingChannels/get
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   id?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     id?: string
       *     name?: string
       *     exchangeRate?: number
       *     description?: string
       *     createdAt?: string
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_business_trading_channels_get<
        Config extends Alova2MethodConfig<ApiResultOfTradingChannel> & {
          params: {
            id?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfTradingChannel, 'general.get_api_business_trading_channels_get', Config>;
      /**
       * ---
       *
       * [POST] 创建交易渠道
       *
       * **path:** /api/Business/TradingChannels/create
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   id?: string
       *   name?: string
       *   exchangeRate?: number
       *   description?: string
       *   createdAt?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     id?: string
       *     name?: string
       *     exchangeRate?: number
       *     description?: string
       *     createdAt?: string
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      post_api_business_trading_channels_create<
        Config extends Alova2MethodConfig<ApiResultOfTradingChannel> & {
          data: TradingChannel;
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfTradingChannel, 'general.post_api_business_trading_channels_create', Config>;
      /**
       * ---
       *
       * [PUT] 更新交易渠道
       *
       * **path:** /api/Business/TradingChannels/update
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   id?: string
       *   name?: string
       *   exchangeRate?: number
       *   description?: string
       *   createdAt?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     id?: string
       *     name?: string
       *     exchangeRate?: number
       *     description?: string
       *     createdAt?: string
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      put_api_business_trading_channels_update<
        Config extends Alova2MethodConfig<ApiResultOfTradingChannel> & {
          data: TradingChannel;
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfTradingChannel, 'general.put_api_business_trading_channels_update', Config>;
      /**
       * ---
       *
       * [DELETE] 删除交易渠道
       *
       * **path:** /api/Business/TradingChannels/delete
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   id?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     id?: string
       *     name?: string
       *     exchangeRate?: number
       *     description?: string
       *     createdAt?: string
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      delete_api_business_trading_channels_delete<
        Config extends Alova2MethodConfig<ApiResultOfTradingChannel> & {
          params: {
            id?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfTradingChannel, 'general.delete_api_business_trading_channels_delete', Config>;
      /**
       * ---
       *
       * [POST] 批量删除交易渠道
       *
       * **path:** /api/Business/TradingChannels/deletes
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = string[]
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      post_api_business_trading_channels_deletes<
        Config extends Alova2MethodConfig<ApiResult> & {
          data: string[];
        }
      >(
        config: Config
      ): Alova2Method<ApiResult, 'general.post_api_business_trading_channels_deletes', Config>;
      /**
       * ---
       *
       * [GET] 获取用户资产日志列表
       *
       * **path:** /api/Business/UserAssetLogs/list
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   startTime?: string
       *   endTime?: string
       *   type?: string
       *   changeType?: string
       *   userId?: string
       *   keyword?: string
       *   page?: number
       *   pagesize?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     // [items] start
       *     // [items] end
       *     list?: Array<{
       *       id?: string
       *       userId?: string
       *       userName?: string
       *       assetType?: number
       *       changeType?: number
       *       value?: number
       *       balance?: number
       *       description?: string
       *       time?: string
       *     }>
       *     page?: number
       *     pageSize?: number
       *     totalPageCount?: number
       *     totalItemCount?: number
       *     extendData?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_business_user_asset_logs_list<
        Config extends Alova2MethodConfig<ApiResultOfPageListOfUserAssetLog> & {
          params: {
            startTime?: string;
            endTime?: string;
            type?: string;
            changeType?: string;
            userId?: string;
            keyword?: string;
            page?: number;
            pagesize?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfPageListOfUserAssetLog, 'general.get_api_business_user_asset_logs_list', Config>;
      /**
       * ---
       *
       * [GET] 获取用户资产日志详情
       *
       * **path:** /api/Business/UserAssetLogs/get
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   id?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     id?: string
       *     userId?: string
       *     userName?: string
       *     assetType?: number
       *     changeType?: number
       *     value?: number
       *     balance?: number
       *     description?: string
       *     time?: string
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_business_user_asset_logs_get<
        Config extends Alova2MethodConfig<ApiResultOfUserAssetLog> & {
          params: {
            id?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfUserAssetLog, 'general.get_api_business_user_asset_logs_get', Config>;
      /**
       * ---
       *
       * [GET] 获取用户订单列表
       *
       * **path:** /api/Business/UserOrders/list
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   startTime?: string
       *   endTime?: string
       *   assetType?: string
       *   status?: string
       *   userId?: string
       *   channelId?: string
       *   keyword?: string
       *   page?: number
       *   pagesize?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     // [items] start
       *     // [items] end
       *     list?: Array<{
       *       id?: string
       *       userId?: string
       *       userName?: string
       *       assetType?: number
       *       amount?: number
       *       status?: number
       *       time?: string
       *       description?: string
       *       config?: {
       *         walletId?: string
       *         channelId?: string
       *         channelName?: string
       *         channelRate?: number
       *       } | null
       *     }>
       *     page?: number
       *     pageSize?: number
       *     totalPageCount?: number
       *     totalItemCount?: number
       *     extendData?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_business_user_orders_list<
        Config extends Alova2MethodConfig<ApiResultOfPageListOfUserOrder> & {
          params: {
            startTime?: string;
            endTime?: string;
            assetType?: string;
            status?: string;
            userId?: string;
            channelId?: string;
            keyword?: string;
            page?: number;
            pagesize?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfPageListOfUserOrder, 'general.get_api_business_user_orders_list', Config>;
      /**
       * ---
       *
       * [GET] 获取用户订单详情
       *
       * **path:** /api/Business/UserOrders/get
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   id?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     id?: string
       *     userId?: string
       *     userName?: string
       *     assetType?: number
       *     amount?: number
       *     status?: number
       *     time?: string
       *     description?: string
       *     config?: {
       *       walletId?: string
       *       channelId?: string
       *       channelName?: string
       *       channelRate?: number
       *     } | null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_business_user_orders_get<
        Config extends Alova2MethodConfig<ApiResultOfUserOrder> & {
          params: {
            id?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfUserOrder, 'general.get_api_business_user_orders_get', Config>;
      /**
       * ---
       *
       * [POST] 创建用户订单
       *
       * **path:** /api/Business/UserOrders/create
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   id?: string
       *   userId?: string
       *   userName?: string
       *   assetType?: number
       *   amount?: number
       *   status?: number
       *   time?: string
       *   description?: string
       *   config?: {
       *     walletId?: string
       *     channelId?: string
       *     channelName?: string
       *     channelRate?: number
       *   } | null
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     id?: string
       *     userId?: string
       *     userName?: string
       *     assetType?: number
       *     amount?: number
       *     status?: number
       *     time?: string
       *     description?: string
       *     config?: {
       *       walletId?: string
       *       channelId?: string
       *       channelName?: string
       *       channelRate?: number
       *     } | null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      post_api_business_user_orders_create<
        Config extends Alova2MethodConfig<ApiResultOfUserOrder> & {
          data: UserOrder;
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfUserOrder, 'general.post_api_business_user_orders_create', Config>;
      /**
       * ---
       *
       * [PUT] 完成用户订单
       *
       * **path:** /api/Business/UserOrders/completed
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   id?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     id?: string
       *     userId?: string
       *     userName?: string
       *     assetType?: number
       *     amount?: number
       *     status?: number
       *     time?: string
       *     description?: string
       *     config?: {
       *       walletId?: string
       *       channelId?: string
       *       channelName?: string
       *       channelRate?: number
       *     } | null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      put_api_business_user_orders_completed<
        Config extends Alova2MethodConfig<ApiResultOfUserOrder> & {
          params: {
            id?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfUserOrder, 'general.put_api_business_user_orders_completed', Config>;
      /**
       * ---
       *
       * [DELETE] 删除用户订单
       *
       * **path:** /api/Business/UserOrders/delete
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   id?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     id?: string
       *     userId?: string
       *     userName?: string
       *     assetType?: number
       *     amount?: number
       *     status?: number
       *     time?: string
       *     description?: string
       *     config?: {
       *       walletId?: string
       *       channelId?: string
       *       channelName?: string
       *       channelRate?: number
       *     } | null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      delete_api_business_user_orders_delete<
        Config extends Alova2MethodConfig<ApiResultOfUserOrder> & {
          params: {
            id?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfUserOrder, 'general.delete_api_business_user_orders_delete', Config>;
      /**
       * ---
       *
       * [POST] 批量删除用户订单
       *
       * **path:** /api/Business/UserOrders/deletes
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = string[]
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      post_api_business_user_orders_deletes<
        Config extends Alova2MethodConfig<ApiResult> & {
          data: string[];
        }
      >(
        config: Config
      ): Alova2Method<ApiResult, 'general.post_api_business_user_orders_deletes', Config>;
      /**
       * ---
       *
       * [GET] 获取用户团队关系列表
       *
       * **path:** /api/Business/UserTeamMaps/list
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   userId?: string
       *   parentId?: string
       *   includeParent?: boolean
       *   level?: number
       *   keyword?: string
       *   page?: number
       *   pagesize?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     // [items] start
       *     // [items] end
       *     list?: Array<{
       *       id?: string
       *       userId?: string
       *       userName?: string
       *       commissionRate?: number
       *       usdtValue?: number
       *       bondValue?: number
       *       parentUserId?: string | null
       *       parentUserName?: string | null
       *       level?: number
       *       ancestorPath?: string
       *       descendantCount?: number
       *       createdAt?: string
       *     }>
       *     page?: number
       *     pageSize?: number
       *     totalPageCount?: number
       *     totalItemCount?: number
       *     extendData?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_business_user_team_maps_list<
        Config extends Alova2MethodConfig<ApiResultOfPageListOfUserTeamMap> & {
          params: {
            userId?: string;
            parentId?: string;
            includeParent?: boolean;
            level?: number;
            keyword?: string;
            page?: number;
            pagesize?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfPageListOfUserTeamMap, 'general.get_api_business_user_team_maps_list', Config>;
      /**
       * ---
       *
       * [GET] 获取用户团队关系详情
       *
       * **path:** /api/Business/UserTeamMaps/get
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   id?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     id?: string
       *     userId?: string
       *     userName?: string
       *     commissionRate?: number
       *     usdtValue?: number
       *     bondValue?: number
       *     parentUserId?: string | null
       *     parentUserName?: string | null
       *     level?: number
       *     ancestorPath?: string
       *     descendantCount?: number
       *     createdAt?: string
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_business_user_team_maps_get<
        Config extends Alova2MethodConfig<ApiResultOfUserTeamMap> & {
          params: {
            id?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfUserTeamMap, 'general.get_api_business_user_team_maps_get', Config>;
      /**
       * ---
       *
       * [POST] 创建用户团队关系
       *
       * **path:** /api/Business/UserTeamMaps/create
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   id?: string
       *   userId?: string
       *   userName?: string
       *   commissionRate?: number
       *   usdtValue?: number
       *   bondValue?: number
       *   parentUserId?: string | null
       *   parentUserName?: string | null
       *   level?: number
       *   ancestorPath?: string
       *   descendantCount?: number
       *   createdAt?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     id?: string
       *     userId?: string
       *     userName?: string
       *     commissionRate?: number
       *     usdtValue?: number
       *     bondValue?: number
       *     parentUserId?: string | null
       *     parentUserName?: string | null
       *     level?: number
       *     ancestorPath?: string
       *     descendantCount?: number
       *     createdAt?: string
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      post_api_business_user_team_maps_create<
        Config extends Alova2MethodConfig<ApiResultOfUserTeamMap> & {
          data: UserTeamMap;
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfUserTeamMap, 'general.post_api_business_user_team_maps_create', Config>;
      /**
       * ---
       *
       * [POST] 转移usdt资产给指定用户
       *
       * **path:** /api/Business/UserTeamMaps/transferUsdt
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   fromUserId?: string
       *   toUserId?: string
       *   amount?: number
       *   serviceFee?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      post_api_business_user_team_maps_transfer_usdt<
        Config extends Alova2MethodConfig<ApiResult> & {
          params: {
            fromUserId?: string;
            toUserId?: string;
            amount?: number;
            serviceFee?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResult, 'general.post_api_business_user_team_maps_transfer_usdt', Config>;
      /**
       * ---
       *
       * [PUT] 更新用户团队关系
       *
       * **path:** /api/Business/UserTeamMaps/update
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   id?: string
       *   userId?: string
       *   userName?: string
       *   commissionRate?: number
       *   usdtValue?: number
       *   bondValue?: number
       *   parentUserId?: string | null
       *   parentUserName?: string | null
       *   level?: number
       *   ancestorPath?: string
       *   descendantCount?: number
       *   createdAt?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     id?: string
       *     userId?: string
       *     userName?: string
       *     commissionRate?: number
       *     usdtValue?: number
       *     bondValue?: number
       *     parentUserId?: string | null
       *     parentUserName?: string | null
       *     level?: number
       *     ancestorPath?: string
       *     descendantCount?: number
       *     createdAt?: string
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      put_api_business_user_team_maps_update<
        Config extends Alova2MethodConfig<ApiResultOfUserTeamMap> & {
          data: UserTeamMap;
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfUserTeamMap, 'general.put_api_business_user_team_maps_update', Config>;
      /**
       * ---
       *
       * [DELETE] 删除用户团队关系
       *
       * **path:** /api/Business/UserTeamMaps/delete
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   id?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     id?: string
       *     userId?: string
       *     userName?: string
       *     commissionRate?: number
       *     usdtValue?: number
       *     bondValue?: number
       *     parentUserId?: string | null
       *     parentUserName?: string | null
       *     level?: number
       *     ancestorPath?: string
       *     descendantCount?: number
       *     createdAt?: string
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      delete_api_business_user_team_maps_delete<
        Config extends Alova2MethodConfig<ApiResultOfUserTeamMap> & {
          params: {
            id?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfUserTeamMap, 'general.delete_api_business_user_team_maps_delete', Config>;
      /**
       * ---
       *
       * [POST] 批量删除用户团队关系
       *
       * **path:** /api/Business/UserTeamMaps/deletes
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = string[]
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      post_api_business_user_team_maps_deletes<
        Config extends Alova2MethodConfig<ApiResult> & {
          data: string[];
        }
      >(
        config: Config
      ): Alova2Method<ApiResult, 'general.post_api_business_user_team_maps_deletes', Config>;
    };
  }

  var Business: Business;
}
