/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 后羿 接口文档 | 微信模块 - version v9.0.9.0
 *
 * 后羿 项目接口文档, Powered By .NET 9.0.10
 *
 * OpenAPI version: 3.0.1
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'general.get_api_weixin_custom_service_list': ['GET', '/api/Weixin/CustomService/list'],
  'general.get_api_weixin_drafts_list': ['GET', '/api/Weixin/Drafts/list'],
  'general.get_api_weixin_drafts_get': ['GET', '/api/Weixin/Drafts/get'],
  'general.post_api_weixin_drafts_create': ['POST', '/api/Weixin/Drafts/create'],
  'general.put_api_weixin_drafts_update': ['PUT', '/api/Weixin/Drafts/update'],
  'general.delete_api_weixin_drafts_delete': ['DELETE', '/api/Weixin/Drafts/delete'],
  'general.post_api_weixin_drafts_batch_send_message': ['POST', '/api/Weixin/Drafts/batchSendMessage'],
  'general.post_api_weixin_drafts_publish': ['POST', '/api/Weixin/Drafts/publish'],
  'general.get_api_weixin_free_publish_list': ['GET', '/api/Weixin/FreePublish/list'],
  'general.get_api_weixin_free_publish_get_by_article_id': ['GET', '/api/Weixin/FreePublish/getByArticleId'],
  'general.get_api_weixin_free_publish_get_status': ['GET', '/api/Weixin/FreePublish/getStatus'],
  'general.delete_api_weixin_free_publish_delete': ['DELETE', '/api/Weixin/FreePublish/delete'],
  'general.post_api_weixin_free_publish_send_template_message': ['POST', '/api/Weixin/FreePublish/sendTemplateMessage'],
  'general.get_api_weixin_materials_get_image': ['GET', '/api/Weixin/Materials/getImage'],
  'general.get_api_weixin_materials_get_news': ['GET', '/api/Weixin/Materials/getNews'],
  'general.get_api_weixin_materials_get_video': ['GET', '/api/Weixin/Materials/getVideo'],
  'general.delete_api_weixin_materials_delete': ['DELETE', '/api/Weixin/Materials/delete'],
  'general.get_api_weixin_menus_get': ['GET', '/api/Weixin/Menus/get'],
  'general.post_api_weixin_menus_update': ['POST', '/api/Weixin/Menus/update'],
  'general.get_api_weixin_mp_create_scene_qrcode': ['GET', '/api/Weixin/Mp/createSceneQrcode'],
  'general.get_api_weixin_mp_create_limit_scene_qrcode': ['GET', '/api/Weixin/Mp/createLimitSceneQrcode'],
  'general.get_api_weixin_mp_services': ['GET', '/api/Weixin/MpServices'],
  'general.post_api_weixin_mp_services': ['POST', '/api/Weixin/MpServices'],
  'general.get_api_weixin_o_auth_user_info_callback': ['GET', '/api/Weixin/OAuth/UserInfoCallback'],
  'general.get_api_weixin_wx_open_on_login': ['GET', '/api/Weixin/WxOpen/onLogin'],
  'general.post_api_weixin_wx_open_decrypt_user_info': ['POST', '/api/Weixin/WxOpen/DecryptUserInfo'],
  'general.post_api_weixin_wx_open_decrypt_phone_number': ['POST', '/api/Weixin/WxOpen/DecryptPhoneNumber'],
  'general.post_api_weixin_wx_open_get_user_phone_number_from_code': [
    'POST',
    '/api/Weixin/WxOpen/GetUserPhoneNumberFromCode'
  ],
  'general.get_api_weixin_wx_open_generate_wxcode': ['GET', '/api/Weixin/WxOpen/GenerateWxcode'],
  'general.post_api_weixin_wx_pay_create_unifiedorder': ['POST', '/api/Weixin/WxPay/CreateUnifiedorder'],
  'general.post_api_weixin_wx_pay_payment_notify': ['POST', '/api/Weixin/WxPay/paymentNotify'],
  'general.get_api_weixin_wx_pay_query': ['GET', '/api/Weixin/WxPay/Query'],
  'general.post_api_weixin_wx_pay_refund': ['POST', '/api/Weixin/WxPay/Refund'],
  'general.post_api_weixin_wx_pay_refund_notify': ['POST', '/api/Weixin/WxPay/refundNotify'],
  'general.post_api_weixin_wx_pay_extract': ['POST', '/api/Weixin/WxPay/extract'],
  'general.get_api_weixin_wx_users_list': ['GET', '/api/Weixin/WxUsers/List'],
  'general.get_api_weixin_wx_users_get': ['GET', '/api/Weixin/WxUsers/get'],
  'general.post_api_weixin_wx_users_create': ['POST', '/api/Weixin/WxUsers/Create'],
  'general.put_api_weixin_wx_users_update': ['PUT', '/api/Weixin/WxUsers/Update'],
  'general.delete_api_weixin_wx_users_delete': ['DELETE', '/api/Weixin/WxUsers/Delete'],
  'general.post_api_weixin_wx_users_sync': ['POST', '/api/Weixin/WxUsers/sync']
};
