/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * TNT.WebApi 接口文档 | 微信模块 - version v10.0.1.0
 *
 * TNT.WebApi 项目接口文档, Powered By .NET 10.0.1
 *
 * OpenAPI version: 3.1.1
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'customService.getCustomServiceList': ['GET', '/api/Weixin/CustomService/list'],
  'draft.getDraftList': ['GET', '/api/Weixin/Drafts/list'],
  'draft.getDraft': ['GET', '/api/Weixin/Drafts/get'],
  'draft.createDraft': ['POST', '/api/Weixin/Drafts/create'],
  'draft.updateDraft': ['PUT', '/api/Weixin/Drafts/update'],
  'draft.deleteDraft': ['DELETE', '/api/Weixin/Drafts/delete'],
  'draft.batchSendMessage': ['POST', '/api/Weixin/Drafts/batchSendMessage'],
  'draft.publishDraft': ['POST', '/api/Weixin/Drafts/publish'],
  'freePublish.getFreePublishList': ['GET', '/api/Weixin/FreePublish/list'],
  'freePublish.getFreePublishByArticleId': ['GET', '/api/Weixin/FreePublish/getByArticleId'],
  'freePublish.getFreePublishStatus': ['GET', '/api/Weixin/FreePublish/getStatus'],
  'freePublish.deleteFreePublish': ['DELETE', '/api/Weixin/FreePublish/delete'],
  'freePublish.sendTemplateMessage': ['POST', '/api/Weixin/FreePublish/sendTemplateMessage'],
  'material.getImageMaterial': ['GET', '/api/Weixin/Materials/getImage'],
  'material.getNewsMaterial': ['GET', '/api/Weixin/Materials/getNews'],
  'material.getVideoMaterial': ['GET', '/api/Weixin/Materials/getVideo'],
  'material.deleteMaterial': ['DELETE', '/api/Weixin/Materials/delete'],
  'menu.getMenu': ['GET', '/api/Weixin/Menus/get'],
  'menu.updateMenu': ['POST', '/api/Weixin/Menus/update'],
  'mp.createSceneQrcode': ['GET', '/api/Weixin/Mp/createMpSceneQrcode'],
  'mp.createLimitSceneQrcode': ['GET', '/api/Weixin/Mp/createMpLimitSceneQrcode'],
  'mpService.getMpService': ['GET', '/api/Weixin/MpServices'],
  'mpService.postMpService': ['POST', '/api/Weixin/MpServices'],
  'oAuth.UserInfoCallback': ['GET', '/api/Weixin/OAuth/UserInfoCallback'],
  'wxOpen.onLogin': ['GET', '/api/Weixin/WxOpen/onLogin'],
  'wxOpen.decryptUserInfo': ['POST', '/api/Weixin/WxOpen/DecryptUserInfo'],
  'wxOpen.decryptPhoneNumber': ['POST', '/api/Weixin/WxOpen/DecryptPhoneNumber'],
  'wxOpen.getUserPhoneNumberFromCode': ['POST', '/api/Weixin/WxOpen/GetUserPhoneNumberFromCode'],
  'wxOpen.generateWxcode': ['GET', '/api/Weixin/WxOpen/GenerateWxcode'],
  'wxOpen.generateScheme': ['GET', '/api/Weixin/WxOpen/generateScheme'],
  'wxOpen.generateUrlLink': ['GET', '/api/Weixin/WxOpen/generateUrlLink'],
  'wxPay.createWxPayUnifiedorder': ['POST', '/api/Weixin/WxPay/CreateUnifiedorder'],
  'wxPay.wxPayPaymentNotify': ['POST', '/api/Weixin/WxPay/paymentNotify'],
  'wxPay.queryWxPay': ['GET', '/api/Weixin/WxPay/Query'],
  'wxPay.refundWxPay': ['POST', '/api/Weixin/WxPay/Refund'],
  'wxPay.refundNotifyWxPay': ['POST', '/api/Weixin/WxPay/refundNotify'],
  'wxPay.extractWxPay': ['POST', '/api/Weixin/WxPay/extract'],
  'wxUser.getWxUserList': ['GET', '/api/Weixin/WxUsers/List'],
  'wxUser.getWxUser': ['GET', '/api/Weixin/WxUsers/get'],
  'wxUser.createWxUser': ['POST', '/api/Weixin/WxUsers/Create'],
  'wxUser.updateWxUser': ['PUT', '/api/Weixin/WxUsers/Update'],
  'wxUser.deleteWxUser': ['DELETE', '/api/Weixin/WxUsers/Delete'],
  'wxUser.deleteWxUsers': ['DELETE', '/api/Weixin/WxUsers/deletes'],
  'wxUser.syncWxUser': ['POST', '/api/Weixin/WxUsers/sync']
};
