/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 后羿 接口文档 | 微信模块 - version v9.0.9.0
 *
 * 后羿 项目接口文档, Powered By .NET 9.0.10
 *
 * OpenAPI version: 3.0.1
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'customService.GetCustomServiceList': ['GET', '/api/Weixin/CustomService/list'],
  'draft.GetDraftList': ['GET', '/api/Weixin/Drafts/list'],
  'draft.GetDraft': ['GET', '/api/Weixin/Drafts/get'],
  'draft.CreateDraft': ['POST', '/api/Weixin/Drafts/create'],
  'draft.UpdateDraft': ['PUT', '/api/Weixin/Drafts/update'],
  'draft.DeleteDraft': ['DELETE', '/api/Weixin/Drafts/delete'],
  'draft.BatchSendMessage': ['POST', '/api/Weixin/Drafts/batchSendMessage'],
  'draft.PublishDraft': ['POST', '/api/Weixin/Drafts/publish'],
  'freePublish.GetFreePublishList': ['GET', '/api/Weixin/FreePublish/list'],
  'freePublish.GetFreePublishByArticleId': ['GET', '/api/Weixin/FreePublish/getByArticleId'],
  'freePublish.GetFreePublishStatus': ['GET', '/api/Weixin/FreePublish/getStatus'],
  'freePublish.DeleteFreePublish': ['DELETE', '/api/Weixin/FreePublish/delete'],
  'freePublish.SendFreePublishTemplateMessage': ['POST', '/api/Weixin/FreePublish/sendTemplateMessage'],
  'material.GetImage': ['GET', '/api/Weixin/Materials/getImage'],
  'material.GetNews': ['GET', '/api/Weixin/Materials/getNews'],
  'material.GetVideo': ['GET', '/api/Weixin/Materials/getVideo'],
  'material.DeleteMaterial': ['DELETE', '/api/Weixin/Materials/delete'],
  'menu.GetMenu': ['GET', '/api/Weixin/Menus/get'],
  'menu.UpdateMenu': ['POST', '/api/Weixin/Menus/update'],
  'mp.CreateSceneQrCode': ['GET', '/api/Weixin/Mp/createSceneQrcode'],
  'mp.CreateLimitSceneQrCode': ['GET', '/api/Weixin/Mp/createLimitSceneQrcode'],
  'mpService.GetWeixinServices': ['GET', '/api/Weixin/MpServices'],
  'mpService.PostWeixinServices': ['POST', '/api/Weixin/MpServices'],
  'oAuth.UserInfoCallback': ['GET', '/api/Weixin/OAuth/UserInfoCallback'],
  'wxOpen.OnLogin': ['GET', '/api/Weixin/WxOpen/onLogin'],
  'wxOpen.DecryptUserInfo': ['POST', '/api/Weixin/WxOpen/DecryptUserInfo'],
  'wxOpen.DecryptPhoneNumber': ['POST', '/api/Weixin/WxOpen/DecryptPhoneNumber'],
  'wxOpen.GetUserPhoneNumberFromCode': ['POST', '/api/Weixin/WxOpen/GetUserPhoneNumberFromCode'],
  'wxOpen.GenerateWxcode': ['GET', '/api/Weixin/WxOpen/GenerateWxcode'],
  'wxPay.CreateUnifiedorder': ['POST', '/api/Weixin/WxPay/CreateUnifiedorder'],
  'wxPay.paymentNotify': ['POST', '/api/Weixin/WxPay/paymentNotify'],
  'wxPay.Query': ['GET', '/api/Weixin/WxPay/Query'],
  'wxPay.Refund': ['POST', '/api/Weixin/WxPay/Refund'],
  'wxPay.refundNotify': ['POST', '/api/Weixin/WxPay/refundNotify'],
  'wxPay.extract': ['POST', '/api/Weixin/WxPay/extract'],
  'wxUser.getWxUserList': ['GET', '/api/Weixin/WxUsers/List'],
  'wxUser.getWxUser': ['GET', '/api/Weixin/WxUsers/get'],
  'wxUser.createWxUser': ['POST', '/api/Weixin/WxUsers/Create'],
  'wxUser.updateWxUser': ['PUT', '/api/Weixin/WxUsers/Update'],
  'wxUser.deleteWxUser': ['DELETE', '/api/Weixin/WxUsers/Delete'],
  'wxUser.syncWxUser': ['POST', '/api/Weixin/WxUsers/sync']
};
