/* tslint:disable */
/* eslint-disable */
/**
 * 后羿 接口文档 | 微信模块 - version v9.0.9.0
 *
 * 后羿 项目接口文档, Powered By .NET 9.0.10
 *
 * OpenAPI version: 3.0.1
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from './index';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export interface DraftModel {
  title?: string | null;
  author?: string | null;
  digest?: string | null;
  content?: string | null;
  content_source_url?: string | null;
  thumb_media_id?: string | null;
  show_cover_pic?: string | null;
  need_open_comment?: number;
  only_fans_can_comment?: number;
}
export interface NewsInfoItem {
  title?: string | null;
  author?: string | null;
  digest?: string | null;
  show_cover?: number;
  cover_url?: string | null;
  content_url?: string | null;
  source_url?: string | null;
}
export type NewsInfo = {
  list?: NewsInfoItem[] | null;
} | null;
export interface MenuFull_RootButton {
  type?: string | null;
  key?: string | null;
  name?: string | null;
  url?: string | null;
  news_info?: NewsInfo;
  appid?: string | null;
  pagepath?: string | null;
  media_id?: string | null;
  article_id?: string | null;
  sub_button?: null[] | null;
}
export type MenuFull_ButtonGroup = {
  button?: MenuFull_RootButton[] | null;
} | null;
export type MenuMatchRule = {
  tag_id?: string | null;
  group_id?: string | null;
  sex?: string | null;
  country?: string | null;
  province?: string | null;
  city?: string | null;
  client_platform_type?: string | null;
  language?: string | null;
} | null;
export interface MenuFull_ConditionalButtonGroup {
  matchrule?: MenuMatchRule;
  menuid?: number;
  button?: null[] | null;
}
export type ReturnCode = number;
export interface GetMenuResultFull {
  menu?: MenuFull_ButtonGroup;
  conditionalmenu?: MenuFull_ConditionalButtonGroup[] | null;
  errcode?: ReturnCode;
  errorCodeValue?: number;
  errmsg?: string | null;
  p2PData?: null;
  hints?: null;
}
export interface PostModel {
  domainId?: string | null;
  appId?: string | null;
  signature?: string | null;
  msg_Signature?: string | null;
  timestamp?: string | null;
  nonce?: string | null;
  token?: string | null;
  encodingAESKey?: string | null;
}
export interface EncryptedDataModel {
  sessionId?: string;
  encryptedData?: string;
  iv?: string;
}
export type WxUserType = number;
export interface WxUser {
  openId: string;
  unionId?: string;
  nickName: string;
  avatarUrl?: string;
  sex?: number;
  country?: string;
  province?: string;
  city?: string;
  phoneNumber?: string;
  identityNumber?: string;
  description?: string;
  isSubscribe?: boolean;
  type?: WxUserType;
  creationDate?: string;
  lastActiveDate?: string;
}
export interface CustomInfo_Json {
  kf_account?: string | null;
  kf_nick?: string | null;
  kf_id?: number;
  kf_headimgurl?: string | null;
  kf_wx?: string | null;
  invite_wx?: string | null;
  invite_expire_time?: number;
  invite_status?: string | null;
}
export type CustomInfoJson = {
  kf_list?: CustomInfo_Json[] | null;
  errcode?: ReturnCode;
  errorCodeValue?: number;
  errmsg?: string | null;
  p2PData?: null;
  hints?: null;
} | null;
export interface ApiResultOfCustomInfoJson {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: CustomInfoJson;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export interface BaseButton {
  name?: string | null;
}
export type ButtonGroupBase = {
  button?: BaseButton[] | null;
} | null;
export interface ConditionalButtonGroup {
  matchrule?: MenuMatchRule;
  menuid?: number;
  button?: null[] | null;
}
export type GetMenuResult = {
  menu?: ButtonGroupBase;
  conditionalmenu?: ConditionalButtonGroup[] | null;
  errcode?: ReturnCode;
  errorCodeValue?: number;
  errmsg?: string | null;
  p2PData?: null;
  hints?: null;
} | null;
export interface ApiResultOfGetMenuResult {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: GetMenuResult;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export interface Draft_Content_Item {
  url?: string | null;
  title?: string | null;
  author?: string | null;
  digest?: string | null;
  content?: string | null;
  content_source_url?: string | null;
  thumb_media_id?: string | null;
  show_cover_pic?: string | null;
  need_open_comment?: number;
  only_fans_can_comment?: number;
}
export type Draft_Content = {
  news_item?: Draft_Content_Item[] | null;
} | null;
export interface DraftList_Item {
  media_id?: string | null;
  content?: Draft_Content;
  update_time?: number;
}
export type PageListOfDraftList_Item = {
  list?: DraftList_Item[];
  page?: number;
  pageSize?: number;
  totalPageCount?: number;
  totalItemCount?: number;
  extendData?: null;
} | null;
export interface ApiResultOfPageListOfDraftList_Item {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: PageListOfDraftList_Item;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export interface DraftItem {
  title?: string | null;
  author?: string | null;
  digest?: string | null;
  content?: string | null;
  content_source_url?: string | null;
  thumb_media_id?: string | null;
  show_cover_pic?: number;
  need_open_comment?: number;
  only_fans_can_comment?: number;
  url?: string | null;
}
export type GetDraftResultJson = {
  news_item?: DraftItem[] | null;
  errcode?: ReturnCode;
  errorCodeValue?: number;
  errmsg?: string | null;
  p2PData?: null;
  hints?: null;
} | null;
export interface ApiResultOfGetDraftResultJson {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: GetDraftResultJson;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export type AddDraftResultJson = {
  media_id?: string | null;
  errcode?: ReturnCode;
  errorCodeValue?: number;
  errmsg?: string | null;
  p2PData?: null;
  hints?: null;
} | null;
export interface ApiResultOfAddDraftResultJson {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: AddDraftResultJson;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export type WxJsonResult = {
  errcode?: number;
  errorCodeValue?: number;
  errmsg?: string | null;
  p2PData?: null;
  hints?: null;
} | null;
export interface ApiResultOfWxJsonResult {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: WxJsonResult;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export type UploadMediaFileType = number;
export type SendResult = {
  type?: number;
  msg_id?: string | null;
  msg_data_id?: string | null;
  errcode?: ReturnCode;
  errorCodeValue?: number;
  errmsg?: string | null;
  p2PData?: null;
  hints?: null;
} | null;
export interface ApiResultOfSendResult {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: SendResult;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export type SubmitFreePublishResultJson = {
  publish_id?: string | null;
  errcode?: ReturnCode;
  errorCodeValue?: number;
  errmsg?: string | null;
  p2PData?: null;
  hints?: null;
} | null;
export interface ApiResultOfSubmitFreePublishResultJson {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: SubmitFreePublishResultJson;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export interface FreePublishGetArticleItemJson {
  is_deleted?: boolean;
  url?: string | null;
  title?: string | null;
  author?: string | null;
  digest?: string | null;
  content?: string | null;
  content_source_url?: string | null;
  thumb_media_id?: string | null;
  show_cover_pic?: string | null;
  need_open_comment?: number;
  only_fans_can_comment?: number;
}
export type FreePublishGetArticleResultJson = {
  news_item?: FreePublishGetArticleItemJson[] | null;
  errcode?: ReturnCode;
  errorCodeValue?: number;
  errmsg?: string | null;
  p2PData?: null;
  hints?: null;
} | null;
export interface FreePublishList_Item {
  article_id?: string | null;
  content?: FreePublishGetArticleResultJson;
  update_time?: number;
}
export type PageListOfFreePublishList_Item = {
  list?: FreePublishList_Item[];
  page?: number;
  pageSize?: number;
  totalPageCount?: number;
  totalItemCount?: number;
  extendData?: null;
} | null;
export interface ApiResultOfPageListOfFreePublishList_Item {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: PageListOfFreePublishList_Item;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export type FreePublishGetArticleResultJson2 = {
  news_item?: FreePublishGetArticleItemJson[] | null;
  errcode?: ReturnCode;
  errorCodeValue?: number;
  errmsg?: string | null;
  p2PData?: null;
  hints?: null;
} | null;
export interface ApiResultOfFreePublishGetArticleResultJson {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: FreePublishGetArticleResultJson2;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export interface FreePublish_Item {
  idx?: number;
  article_url?: string | null;
}
export type FreePublish_Article_detail = {
  count?: number;
  item?: FreePublish_Item[] | null;
} | null;
export type GetFreePublishResultJson = {
  publish_id?: string | null;
  publish_status?: number;
  article_id?: string | null;
  article_detail?: FreePublish_Article_detail;
  fail_idx?: number[] | null;
  errcode?: ReturnCode;
  errorCodeValue?: number;
  errmsg?: string | null;
  p2PData?: null;
  hints?: null;
} | null;
export interface ApiResultOfGetFreePublishResultJson {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: GetFreePublishResultJson;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export type ValueTupleOfintAndint = object;
export interface ApiResultOfValueTupleOfintAndint {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: ValueTupleOfintAndint;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export interface ForeverNewsItem {
  url?: string | null;
  thumb_media_id?: string | null;
  author?: string | null;
  title?: string | null;
  content_source_url?: string | null;
  content?: string | null;
  digest?: string | null;
  show_cover_pic?: string | null;
  thumb_url?: string | null;
  need_open_comment?: number;
  only_fans_can_comment?: number;
}
export type GetNewsResultJson = {
  news_item?: ForeverNewsItem[] | null;
  errcode?: ReturnCode;
  errorCodeValue?: number;
  errmsg?: string | null;
  p2PData?: null;
  hints?: null;
} | null;
export interface ApiResultOfGetNewsResultJson {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: GetNewsResultJson;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export type GetForeverMediaVideoResultJson = {
  title?: string | null;
  description?: string | null;
  down_url?: string | null;
  errcode?: ReturnCode;
  errorCodeValue?: number;
  errmsg?: string | null;
  p2PData?: null;
  hints?: null;
} | null;
export interface ApiResultOfGetForeverMediaVideoResultJson {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: GetForeverMediaVideoResultJson;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export interface ApiResultOfstring {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: string | null;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export interface ApiResult {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: null;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export type Watermark = {
  appid?: string | null;
  timestamp?: number;
  dateTimeStamp?: string;
} | null;
export type DecodedUserInfo = {
  openId?: string | null;
  nickName?: string | null;
  gender?: number;
  city?: string | null;
  province?: string | null;
  country?: string | null;
  avatarUrl?: string | null;
  unionId?: string | null;
  watermark?: Watermark;
} | null;
export interface ApiResultOfDecodedUserInfo {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: DecodedUserInfo;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export type Payer = {
  openid?: string | null;
  sp_openid?: string | null;
  sub_openid?: string | null;
} | null;
export type Scene_Info = {
  device_id?: string | null;
} | null;
export type Amount = {
  total?: number;
  payer_total?: number;
  currency?: string | null;
  payer_currency?: string | null;
  scene_info?: Scene_Info;
} | null;
export interface Goods_Detail {
  goods_id?: string | null;
  quantity?: number;
  unit_price?: number;
  discount_amount?: number;
  goods_remark?: string | null;
}
export interface Promotion_Detail {
  coupon_id?: string | null;
  name?: string | null;
  scope?: string | null;
  type?: string | null;
  amount?: number;
  stock_id?: string | null;
  wechatpay_contribute?: string | null;
  merchant_contribute?: string | null;
  other_contribute?: string | null;
  currency?: string | null;
  goods_detail?: Goods_Detail[] | null;
}
export type TenPayApiResultCode = {
  success?: boolean;
  stateCode?: string | null;
  errorCode?: string | null;
  errorMessage?: string | null;
  solution?: string | null;
  additional?: string | null;
} | null;
export type OrderReturnJson = {
  appid?: string | null;
  mchid?: string | null;
  out_trade_no?: string | null;
  transaction_id?: string | null;
  trade_type?: string | null;
  trade_state?: string | null;
  trade_state_desc?: string | null;
  bank_type?: string | null;
  attach?: string | null;
  success_time?: string;
  payer?: Payer;
  amount?: Amount;
  scene_info?: Scene_Info;
  promotion_detail?: Promotion_Detail[] | null;
  resultCode?: TenPayApiResultCode;
  verifySignSuccess?: boolean | null;
} | null;
export interface ApiResultOfOrderReturnJson {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: OrderReturnJson;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export interface From {
  account?: number;
  amount?: number;
}
export type Amount2 = {
  total?: number;
  refund?: number;
  from?: From[] | null;
  payer_total?: number;
  payer_refund?: number;
  settlement_refund?: number;
  settlement_total?: number;
  discount_refund?: number;
  currency?: string | null;
} | null;
export interface Goods_Detail2 {
  merchant_goods_id?: string | null;
  wechatpay_goods_id?: string | null;
  goods_name?: string | null;
  unit_price?: number;
  refund_amount?: number;
  refund_quantity?: number;
}
export interface Promotion_Detail2 {
  promotion_id?: string | null;
  scope?: string | null;
  type?: string | null;
  amount?: number;
  refund_amount?: number;
  goods_detail?: Goods_Detail2[] | null;
}
export type RefundReturnJson = {
  refund_id?: string | null;
  out_refund_no?: string | null;
  transaction_id?: string | null;
  out_trade_no?: string | null;
  channel?: string | null;
  user_received_account?: string | null;
  success_time?: string;
  create_time?: string | null;
  status?: string | null;
  funds_account?: string | null;
  amount?: Amount2;
  promotion_detail?: Promotion_Detail2[] | null;
  resultCode?: TenPayApiResultCode;
  verifySignSuccess?: boolean | null;
} | null;
export interface ApiResultOfRefundReturnJson {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: RefundReturnJson;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export type ApplicationUser = {
  userName: string;
  email?: string | null;
  name?: string;
  avatarUrl?: string;
  phoneNumber?: string | null;
  description?: string;
  rights?: string;
  rightsList?: string[];
  signature?: string;
  enabled?: boolean;
  date?: string;
  id?: string | null;
  normalizedUserName?: string | null;
  normalizedEmail?: string | null;
  emailConfirmed?: boolean;
  passwordHash?: string | null;
  securityStamp?: string | null;
  concurrencyStamp?: string | null;
  phoneNumberConfirmed?: boolean;
  twoFactorEnabled?: boolean;
  lockoutEnd?: string | null;
  lockoutEnabled?: boolean;
  accessFailedCount?: number;
} | null;
export interface ApiResultOfApplicationUser {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: ApplicationUser;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export type PageListOfWxUser = {
  list?: WxUser[];
  page?: number;
  pageSize?: number;
  totalPageCount?: number;
  totalItemCount?: number;
  extendData?: null;
} | null;
export interface ApiResultOfPageListOfWxUser {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: PageListOfWxUser;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export type WxUser2 = {
  openId: string;
  unionId?: string;
  nickName: string;
  avatarUrl?: string;
  sex?: number;
  country?: string;
  province?: string;
  city?: string;
  phoneNumber?: string;
  identityNumber?: string;
  description?: string;
  isSubscribe?: boolean;
  type?: WxUserType;
  creationDate?: string;
  lastActiveDate?: string;
} | null;
export interface ApiResultOfWxUser {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: WxUser2;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export type SyncApiResult = {
  totalCount?: number;
  count?: number;
} | null;
export interface ApiResultOfSyncApiResult {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: SyncApiResult;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
declare global {
  interface WebApi_Weixin {
    general: {
      /**
       * ---
       *
       * [GET] 获取客服列表
       *
       * **path:** /api/Weixin/CustomService/list
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     kf_list?: Array<{
       *       kf_account?: string | null
       *       kf_nick?: string | null
       *       kf_id?: number
       *       kf_headimgurl?: string | null
       *       kf_wx?: string | null
       *       invite_wx?: string | null
       *       invite_expire_time?: number
       *       invite_status?: string | null
       *     }> | null
       *     errcode?: number
       *     errorCodeValue?: number
       *     errmsg?: string | null
       *     p2PData?: null
       *     hints?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_weixin_custom_service_list<Config extends Alova2MethodConfig<ApiResultOfCustomInfoJson>>(
        config?: Config
      ): Alova2Method<ApiResultOfCustomInfoJson, 'general.get_api_weixin_custom_service_list', Config>;
      /**
       * ---
       *
       * [GET] 获取草稿列表
       *
       * **path:** /api/Weixin/Drafts/list
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   page?: number
       *   pagesize?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     // [items] start
       *     // [items] end
       *     list?: Array<{
       *       media_id?: string | null
       *       content?: {
       *         // [params1] start
       *         // [items] start
       *         // [items] end
       *         // [params1] end
       *         news_item?: Array<{
       *           url?: string | null
       *           title?: string | null
       *           author?: string | null
       *           digest?: string | null
       *           content?: string | null
       *           content_source_url?: string | null
       *           thumb_media_id?: string | null
       *           show_cover_pic?: string | null
       *           need_open_comment?: number
       *           only_fans_can_comment?: number
       *         }> | null
       *       } | null
       *       update_time?: number
       *     }>
       *     page?: number
       *     pageSize?: number
       *     totalPageCount?: number
       *     totalItemCount?: number
       *     extendData?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_weixin_drafts_list<
        Config extends Alova2MethodConfig<ApiResultOfPageListOfDraftList_Item> & {
          params: {
            page?: number;
            pagesize?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfPageListOfDraftList_Item, 'general.get_api_weixin_drafts_list', Config>;
      /**
       * ---
       *
       * [GET] 获取草稿详情
       *
       * **path:** /api/Weixin/Drafts/get
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   mediaid?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     news_item?: Array<{
       *       title?: string | null
       *       author?: string | null
       *       digest?: string | null
       *       content?: string | null
       *       content_source_url?: string | null
       *       thumb_media_id?: string | null
       *       show_cover_pic?: number
       *       need_open_comment?: number
       *       only_fans_can_comment?: number
       *       url?: string | null
       *     }> | null
       *     errcode?: number
       *     errorCodeValue?: number
       *     errmsg?: string | null
       *     p2PData?: null
       *     hints?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_weixin_drafts_get<
        Config extends Alova2MethodConfig<ApiResultOfGetDraftResultJson> & {
          params: {
            mediaid?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfGetDraftResultJson, 'general.get_api_weixin_drafts_get', Config>;
      /**
       * ---
       *
       * [POST] 添加草稿
       *
       * **path:** /api/Weixin/Drafts/create
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = Array<{
       *   title?: string | null
       *   author?: string | null
       *   digest?: string | null
       *   content?: string | null
       *   content_source_url?: string | null
       *   thumb_media_id?: string | null
       *   show_cover_pic?: string | null
       *   need_open_comment?: number
       *   only_fans_can_comment?: number
       * }>
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     media_id?: string | null
       *     errcode?: number
       *     errorCodeValue?: number
       *     errmsg?: string | null
       *     p2PData?: null
       *     hints?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      post_api_weixin_drafts_create<
        Config extends Alova2MethodConfig<ApiResultOfAddDraftResultJson> & {
          data: DraftModel[];
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfAddDraftResultJson, 'general.post_api_weixin_drafts_create', Config>;
      /**
       * ---
       *
       * [PUT] 更新草稿
       *
       * **path:** /api/Weixin/Drafts/update
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   mediaid?: string
       *   index?: number
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   title?: string | null
       *   author?: string | null
       *   digest?: string | null
       *   content?: string | null
       *   content_source_url?: string | null
       *   thumb_media_id?: string | null
       *   show_cover_pic?: string | null
       *   need_open_comment?: number
       *   only_fans_can_comment?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     errcode?: number
       *     errorCodeValue?: number
       *     errmsg?: string | null
       *     p2PData?: null
       *     hints?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      put_api_weixin_drafts_update<
        Config extends Alova2MethodConfig<ApiResultOfWxJsonResult> & {
          params: {
            mediaid?: string;
            index?: number;
          };
          data: DraftModel;
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfWxJsonResult, 'general.put_api_weixin_drafts_update', Config>;
      /**
       * ---
       *
       * [DELETE] 删除草稿
       *
       * **path:** /api/Weixin/Drafts/delete
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   mediaid?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     errcode?: number
       *     errorCodeValue?: number
       *     errmsg?: string | null
       *     p2PData?: null
       *     hints?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      delete_api_weixin_drafts_delete<
        Config extends Alova2MethodConfig<ApiResultOfWxJsonResult> & {
          params: {
            mediaid?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfWxJsonResult, 'general.delete_api_weixin_drafts_delete', Config>;
      /**
       * ---
       *
       * [POST] 群发草稿资讯
       *
       * **path:** /api/Weixin/Drafts/batchSendMessage
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   mediaid?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     type?: number
       *     msg_id?: string | null
       *     msg_data_id?: string | null
       *     errcode?: number
       *     errorCodeValue?: number
       *     errmsg?: string | null
       *     p2PData?: null
       *     hints?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      post_api_weixin_drafts_batch_send_message<
        Config extends Alova2MethodConfig<ApiResultOfSendResult> & {
          params: {
            mediaid?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfSendResult, 'general.post_api_weixin_drafts_batch_send_message', Config>;
      /**
       * ---
       *
       * [POST] 发布草稿
       *
       * **path:** /api/Weixin/Drafts/publish
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   mediaid?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     publish_id?: string | null
       *     errcode?: number
       *     errorCodeValue?: number
       *     errmsg?: string | null
       *     p2PData?: null
       *     hints?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      post_api_weixin_drafts_publish<
        Config extends Alova2MethodConfig<ApiResultOfSubmitFreePublishResultJson> & {
          params: {
            mediaid?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfSubmitFreePublishResultJson, 'general.post_api_weixin_drafts_publish', Config>;
      /**
       * ---
       *
       * [GET] 获取发表记录列表
       *
       * **path:** /api/Weixin/FreePublish/list
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   page?: number
       *   pagesize?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     // [items] start
       *     // [items] end
       *     list?: Array<{
       *       article_id?: string | null
       *       content?: {
       *         // [params1] start
       *         // [items] start
       *         // [items] end
       *         // [params1] end
       *         news_item?: Array<{
       *           is_deleted?: boolean
       *           url?: string | null
       *           title?: string | null
       *           author?: string | null
       *           digest?: string | null
       *           content?: string | null
       *           content_source_url?: string | null
       *           thumb_media_id?: string | null
       *           show_cover_pic?: string | null
       *           need_open_comment?: number
       *           only_fans_can_comment?: number
       *         }> | null
       *         errcode?: number
       *         errorCodeValue?: number
       *         errmsg?: string | null
       *         p2PData?: null
       *         hints?: null
       *       } | null
       *       update_time?: number
       *     }>
       *     page?: number
       *     pageSize?: number
       *     totalPageCount?: number
       *     totalItemCount?: number
       *     extendData?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_weixin_free_publish_list<
        Config extends Alova2MethodConfig<ApiResultOfPageListOfFreePublishList_Item> & {
          params: {
            page?: number;
            pagesize?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfPageListOfFreePublishList_Item, 'general.get_api_weixin_free_publish_list', Config>;
      /**
       * ---
       *
       * [GET] 通过 article_id 获取已发布文章
       *
       * **path:** /api/Weixin/FreePublish/getByArticleId
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   articleId?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     news_item?: Array<{
       *       is_deleted?: boolean
       *       url?: string | null
       *       title?: string | null
       *       author?: string | null
       *       digest?: string | null
       *       content?: string | null
       *       content_source_url?: string | null
       *       thumb_media_id?: string | null
       *       show_cover_pic?: string | null
       *       need_open_comment?: number
       *       only_fans_can_comment?: number
       *     }> | null
       *     errcode?: number
       *     errorCodeValue?: number
       *     errmsg?: string | null
       *     p2PData?: null
       *     hints?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_weixin_free_publish_get_by_article_id<
        Config extends Alova2MethodConfig<ApiResultOfFreePublishGetArticleResultJson> & {
          params: {
            articleId?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        ApiResultOfFreePublishGetArticleResultJson,
        'general.get_api_weixin_free_publish_get_by_article_id',
        Config
      >;
      /**
       * ---
       *
       * [GET] 查询发布状态
       *
       * **path:** /api/Weixin/FreePublish/getStatus
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   publishId?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     publish_id?: string | null
       *     publish_status?: number
       *     article_id?: string | null
       *     article_detail?: {
       *       count?: number
       *       // [params1] start
       *       // [items] start
       *       // [items] end
       *       // [params1] end
       *       item?: Array<{
       *         idx?: number
       *         article_url?: string | null
       *       }> | null
       *     } | null
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     fail_idx?: number[] | null
       *     errcode?: number
       *     errorCodeValue?: number
       *     errmsg?: string | null
       *     p2PData?: null
       *     hints?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_weixin_free_publish_get_status<
        Config extends Alova2MethodConfig<ApiResultOfGetFreePublishResultJson> & {
          params: {
            publishId?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfGetFreePublishResultJson, 'general.get_api_weixin_free_publish_get_status', Config>;
      /**
       * ---
       *
       * [DELETE] 删除发表记录
       *
       * **path:** /api/Weixin/FreePublish/delete
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   articleId?: string
       *   index?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     errcode?: number
       *     errorCodeValue?: number
       *     errmsg?: string | null
       *     p2PData?: null
       *     hints?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      delete_api_weixin_free_publish_delete<
        Config extends Alova2MethodConfig<ApiResultOfWxJsonResult> & {
          params: {
            articleId?: string;
            index?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfWxJsonResult, 'general.delete_api_weixin_free_publish_delete', Config>;
      /**
       * ---
       *
       * [POST] 群推发表记录为模板消息
       *
       * **path:** /api/Weixin/FreePublish/sendTemplateMessage
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   articleId?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: object
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      post_api_weixin_free_publish_send_template_message<
        Config extends Alova2MethodConfig<ApiResultOfValueTupleOfintAndint> & {
          params: {
            articleId?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        ApiResultOfValueTupleOfintAndint,
        'general.post_api_weixin_free_publish_send_template_message',
        Config
      >;
      /**
       * ---
       *
       * [GET] 获取图片素材详情
       *
       * **path:** /api/Weixin/Materials/getImage
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   mediaid?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      get_api_weixin_materials_get_image<
        Config extends Alova2MethodConfig<null> & {
          params: {
            mediaid?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<null, 'general.get_api_weixin_materials_get_image', Config>;
      /**
       * ---
       *
       * [GET] 获取图文素材详情
       *
       * **path:** /api/Weixin/Materials/getNews
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   mediaid?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     news_item?: Array<{
       *       url?: string | null
       *       thumb_media_id?: string | null
       *       author?: string | null
       *       title?: string | null
       *       content_source_url?: string | null
       *       content?: string | null
       *       digest?: string | null
       *       show_cover_pic?: string | null
       *       thumb_url?: string | null
       *       need_open_comment?: number
       *       only_fans_can_comment?: number
       *     }> | null
       *     errcode?: number
       *     errorCodeValue?: number
       *     errmsg?: string | null
       *     p2PData?: null
       *     hints?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_weixin_materials_get_news<
        Config extends Alova2MethodConfig<ApiResultOfGetNewsResultJson> & {
          params: {
            mediaid?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfGetNewsResultJson, 'general.get_api_weixin_materials_get_news', Config>;
      /**
       * ---
       *
       * [GET] 获取视频素材详情
       *
       * **path:** /api/Weixin/Materials/getVideo
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   mediaid?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     title?: string | null
       *     description?: string | null
       *     down_url?: string | null
       *     errcode?: number
       *     errorCodeValue?: number
       *     errmsg?: string | null
       *     p2PData?: null
       *     hints?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_weixin_materials_get_video<
        Config extends Alova2MethodConfig<ApiResultOfGetForeverMediaVideoResultJson> & {
          params: {
            mediaid?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfGetForeverMediaVideoResultJson, 'general.get_api_weixin_materials_get_video', Config>;
      /**
       * ---
       *
       * [DELETE] 删除素材
       *
       * **path:** /api/Weixin/Materials/delete
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   mediaid?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     errcode?: number
       *     errorCodeValue?: number
       *     errmsg?: string | null
       *     p2PData?: null
       *     hints?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      delete_api_weixin_materials_delete<
        Config extends Alova2MethodConfig<ApiResultOfWxJsonResult> & {
          params: {
            mediaid?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfWxJsonResult, 'general.delete_api_weixin_materials_delete', Config>;
      /**
       * ---
       *
       * [GET] 获取菜单内容
       *
       * **path:** /api/Weixin/Menus/get
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     menu?: {
       *       // [params1] start
       *       // [items] start
       *       // [items] end
       *       // [params1] end
       *       button?: Array<{
       *         name?: string | null
       *       }> | null
       *     } | null
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     conditionalmenu?: Array<{
       *       matchrule?: {
       *         tag_id?: string | null
       *         group_id?: string | null
       *         sex?: string | null
       *         country?: string | null
       *         province?: string | null
       *         city?: string | null
       *         client_platform_type?: string | null
       *         language?: string | null
       *       } | null
       *       menuid?: number
       *       // [params1] start
       *       // [items] start
       *       // [items] end
       *       // [params1] end
       *       button?: null[] | null
       *     }> | null
       *     errcode?: number
       *     errorCodeValue?: number
       *     errmsg?: string | null
       *     p2PData?: null
       *     hints?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_weixin_menus_get<Config extends Alova2MethodConfig<ApiResultOfGetMenuResult>>(
        config?: Config
      ): Alova2Method<ApiResultOfGetMenuResult, 'general.get_api_weixin_menus_get', Config>;
      /**
       * ---
       *
       * [POST] 更新菜单
       *
       * **path:** /api/Weixin/Menus/update
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   menu?: {
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     button?: Array<{
       *       type?: string | null
       *       key?: string | null
       *       name?: string | null
       *       url?: string | null
       *       news_info?: {
       *         // [params1] start
       *         // [items] start
       *         // [items] end
       *         // [params1] end
       *         list?: Array<{
       *           title?: string | null
       *           author?: string | null
       *           digest?: string | null
       *           show_cover?: number
       *           cover_url?: string | null
       *           content_url?: string | null
       *           source_url?: string | null
       *         }> | null
       *       } | null
       *       appid?: string | null
       *       pagepath?: string | null
       *       media_id?: string | null
       *       article_id?: string | null
       *       // [params1] start
       *       // [items] start
       *       // [items] end
       *       // [params1] end
       *       sub_button?: null[] | null
       *     }> | null
       *   } | null
       *   // [params1] start
       *   // [items] start
       *   // [items] end
       *   // [params1] end
       *   conditionalmenu?: Array<{
       *     matchrule?: {
       *       tag_id?: string | null
       *       group_id?: string | null
       *       sex?: string | null
       *       country?: string | null
       *       province?: string | null
       *       city?: string | null
       *       client_platform_type?: string | null
       *       language?: string | null
       *     } | null
       *     menuid?: number
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     button?: null[] | null
       *   }> | null
       *   errcode?: number
       *   errorCodeValue?: number
       *   errmsg?: string | null
       *   p2PData?: null
       *   hints?: null
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     errcode?: number
       *     errorCodeValue?: number
       *     errmsg?: string | null
       *     p2PData?: null
       *     hints?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      post_api_weixin_menus_update<
        Config extends Alova2MethodConfig<ApiResultOfWxJsonResult> & {
          data: GetMenuResultFull;
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfWxJsonResult, 'general.post_api_weixin_menus_update', Config>;
      /**
       * ---
       *
       * [GET] 创建临时带参二维码
       *
       * **path:** /api/Weixin/Mp/createSceneQrcode
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   scene?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: string | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_weixin_mp_create_scene_qrcode<
        Config extends Alova2MethodConfig<ApiResultOfstring> & {
          params: {
            scene?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfstring, 'general.get_api_weixin_mp_create_scene_qrcode', Config>;
      /**
       * ---
       *
       * [GET] 创建永久带参二维码
       *
       * **path:** /api/Weixin/Mp/createLimitSceneQrcode
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   scene?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: string | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_weixin_mp_create_limit_scene_qrcode<
        Config extends Alova2MethodConfig<ApiResultOfstring> & {
          params: {
            scene?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfstring, 'general.get_api_weixin_mp_create_limit_scene_qrcode', Config>;
      /**
       * ---
       *
       * [GET] 微信后台验证地址
       *
       * **path:** /api/Weixin/MpServices
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   echostr?: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   domainId?: string | null
       *   appId?: string | null
       *   signature?: string | null
       *   msg_Signature?: string | null
       *   timestamp?: string | null
       *   nonce?: string | null
       *   token?: string | null
       *   encodingAESKey?: string | null
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      get_api_weixin_mp_services<
        Config extends Alova2MethodConfig<null> & {
          params: {
            echostr?: string;
          };
          data: PostModel;
        }
      >(
        config: Config
      ): Alova2Method<null, 'general.get_api_weixin_mp_services', Config>;
      /**
       * ---
       *
       * [POST] 微信后台消息处理地址
       *
       * **path:** /api/Weixin/MpServices
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   domainId?: string | null
       *   appId?: string | null
       *   signature?: string | null
       *   msg_Signature?: string | null
       *   timestamp?: string | null
       *   nonce?: string | null
       *   token?: string | null
       *   encodingAESKey?: string | null
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      post_api_weixin_mp_services<
        Config extends Alova2MethodConfig<null> & {
          data: PostModel;
        }
      >(
        config: Config
      ): Alova2Method<null, 'general.post_api_weixin_mp_services', Config>;
      /**
       * ---
       *
       * [GET] OAuth2.0授权回调地址
       *
       * **path:** /api/Weixin/OAuth/UserInfoCallback
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   code?: string
       *   state?: string
       *   returnUrl?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      get_api_weixin_o_auth_user_info_callback<
        Config extends Alova2MethodConfig<null> & {
          params: {
            code?: string;
            state?: string;
            returnUrl?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<null, 'general.get_api_weixin_o_auth_user_info_callback', Config>;
      /**
       * ---
       *
       * [GET] wx.login登陆成功之后发送的请求
       *
       * **path:** /api/Weixin/WxOpen/onLogin
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   code?: string
       *   appKey?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_weixin_wx_open_on_login<
        Config extends Alova2MethodConfig<ApiResult> & {
          params: {
            code?: string;
            appKey?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResult, 'general.get_api_weixin_wx_open_on_login', Config>;
      /**
       * ---
       *
       * [POST] 解密前端getUserInfo返回的加密数据获取用户档案数据
       *
       * **path:** /api/Weixin/WxOpen/DecryptUserInfo
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   sessionId?: string
       *   encryptedData?: string
       *   iv?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     openId?: string | null
       *     nickName?: string | null
       *     gender?: number
       *     city?: string | null
       *     province?: string | null
       *     country?: string | null
       *     avatarUrl?: string | null
       *     unionId?: string | null
       *     watermark?: {
       *       appid?: string | null
       *       timestamp?: number
       *       dateTimeStamp?: string
       *     } | null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      post_api_weixin_wx_open_decrypt_user_info<
        Config extends Alova2MethodConfig<ApiResultOfDecodedUserInfo> & {
          data: EncryptedDataModel;
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfDecodedUserInfo, 'general.post_api_weixin_wx_open_decrypt_user_info', Config>;
      /**
       * ---
       *
       * [POST] 解密电话号码
       *
       * **path:** /api/Weixin/WxOpen/DecryptPhoneNumber
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   sessionId?: string
       *   encryptedData?: string
       *   iv?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: string | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      post_api_weixin_wx_open_decrypt_phone_number<
        Config extends Alova2MethodConfig<ApiResultOfstring> & {
          data: EncryptedDataModel;
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfstring, 'general.post_api_weixin_wx_open_decrypt_phone_number', Config>;
      /**
       * ---
       *
       * [POST] 将code换取用户手机号
       *
       * **path:** /api/Weixin/WxOpen/GetUserPhoneNumberFromCode
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   code?: string
       *   appKey?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: string | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      post_api_weixin_wx_open_get_user_phone_number_from_code<
        Config extends Alova2MethodConfig<ApiResultOfstring> & {
          params: {
            code?: string;
            appKey?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfstring, 'general.post_api_weixin_wx_open_get_user_phone_number_from_code', Config>;
      /**
       * ---
       *
       * [GET] 生成小程序码
       *
       * **path:** /api/Weixin/WxOpen/GenerateWxcode
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   path?: string
       *   scene?: string
       *   appKey?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      get_api_weixin_wx_open_generate_wxcode<
        Config extends Alova2MethodConfig<null> & {
          params: {
            path?: string;
            scene?: string;
            appKey?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<null, 'general.get_api_weixin_wx_open_generate_wxcode', Config>;
      /**
       * ---
       *
       * [POST] 统一下单
       *
       * **path:** /api/Weixin/WxPay/CreateUnifiedorder
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   openId?: string
       *   orderNum?: string
       *   body?: string
       *   price?: string
       *   notifyUrl?: string
       *   attach?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      post_api_weixin_wx_pay_create_unifiedorder<
        Config extends Alova2MethodConfig<ApiResult> & {
          params: {
            openId?: string;
            orderNum?: string;
            body?: string;
            price?: string;
            notifyUrl?: string;
            attach?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResult, 'general.post_api_weixin_wx_pay_create_unifiedorder', Config>;
      /**
       * ---
       *
       * [POST] 支付成功通知
       *
       * **path:** /api/Weixin/WxPay/paymentNotify
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      post_api_weixin_wx_pay_payment_notify<Config extends Alova2MethodConfig<null>>(
        config?: Config
      ): Alova2Method<null, 'general.post_api_weixin_wx_pay_payment_notify', Config>;
      /**
       * ---
       *
       * [GET] 查询订单状态
       *
       * **path:** /api/Weixin/WxPay/Query
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   orderNum?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     appid?: string | null
       *     mchid?: string | null
       *     out_trade_no?: string | null
       *     transaction_id?: string | null
       *     trade_type?: string | null
       *     trade_state?: string | null
       *     trade_state_desc?: string | null
       *     bank_type?: string | null
       *     attach?: string | null
       *     success_time?: string
       *     payer?: {
       *       openid?: string | null
       *       sp_openid?: string | null
       *       sub_openid?: string | null
       *     } | null
       *     amount?: {
       *       total?: number
       *       payer_total?: number
       *       currency?: string | null
       *       payer_currency?: string | null
       *       scene_info?: {
       *         device_id?: string | null
       *       } | null
       *     } | null
       *     scene_info?: {
       *       device_id?: string | null
       *     } | null
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     promotion_detail?: Array<{
       *       coupon_id?: string | null
       *       name?: string | null
       *       scope?: string | null
       *       type?: string | null
       *       amount?: number
       *       stock_id?: string | null
       *       wechatpay_contribute?: string | null
       *       merchant_contribute?: string | null
       *       other_contribute?: string | null
       *       currency?: string | null
       *       // [params1] start
       *       // [items] start
       *       // [items] end
       *       // [params1] end
       *       goods_detail?: Array<{
       *         goods_id?: string | null
       *         quantity?: number
       *         unit_price?: number
       *         discount_amount?: number
       *         goods_remark?: string | null
       *       }> | null
       *     }> | null
       *     resultCode?: {
       *       success?: boolean
       *       stateCode?: string | null
       *       errorCode?: string | null
       *       errorMessage?: string | null
       *       solution?: string | null
       *       additional?: string | null
       *     } | null
       *     verifySignSuccess?: boolean | null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_weixin_wx_pay_query<
        Config extends Alova2MethodConfig<ApiResultOfOrderReturnJson> & {
          params: {
            orderNum?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfOrderReturnJson, 'general.get_api_weixin_wx_pay_query', Config>;
      /**
       * ---
       *
       * [POST] 发起退款申请
       *
       * **path:** /api/Weixin/WxPay/Refund
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   orderNum?: string
       *   notifyUrl?: string
       *   proportion?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     refund_id?: string | null
       *     out_refund_no?: string | null
       *     transaction_id?: string | null
       *     out_trade_no?: string | null
       *     channel?: string | null
       *     user_received_account?: string | null
       *     success_time?: string
       *     create_time?: string | null
       *     status?: string | null
       *     funds_account?: string | null
       *     amount?: {
       *       total?: number
       *       refund?: number
       *       // [params1] start
       *       // [items] start
       *       // [items] end
       *       // [params1] end
       *       from?: Array<{
       *         account?: number
       *         amount?: number
       *       }> | null
       *       payer_total?: number
       *       payer_refund?: number
       *       settlement_refund?: number
       *       settlement_total?: number
       *       discount_refund?: number
       *       currency?: string | null
       *     } | null
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     promotion_detail?: Array<{
       *       promotion_id?: string | null
       *       scope?: string | null
       *       type?: string | null
       *       amount?: number
       *       refund_amount?: number
       *       // [params1] start
       *       // [items] start
       *       // [items] end
       *       // [params1] end
       *       goods_detail?: Array<{
       *         merchant_goods_id?: string | null
       *         wechatpay_goods_id?: string | null
       *         goods_name?: string | null
       *         unit_price?: number
       *         refund_amount?: number
       *         refund_quantity?: number
       *       }> | null
       *     }> | null
       *     resultCode?: {
       *       success?: boolean
       *       stateCode?: string | null
       *       errorCode?: string | null
       *       errorMessage?: string | null
       *       solution?: string | null
       *       additional?: string | null
       *     } | null
       *     verifySignSuccess?: boolean | null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      post_api_weixin_wx_pay_refund<
        Config extends Alova2MethodConfig<ApiResultOfRefundReturnJson> & {
          params: {
            orderNum?: string;
            notifyUrl?: string;
            proportion?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfRefundReturnJson, 'general.post_api_weixin_wx_pay_refund', Config>;
      /**
       * ---
       *
       * [POST] 退款成功通知
       *
       * **path:** /api/Weixin/WxPay/refundNotify
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      post_api_weixin_wx_pay_refund_notify<Config extends Alova2MethodConfig<null>>(
        config?: Config
      ): Alova2Method<null, 'general.post_api_weixin_wx_pay_refund_notify', Config>;
      /**
       * ---
       *
       * [POST] 提现
       *
       * **path:** /api/Weixin/WxPay/extract
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   id?: string
       *   userTrueName?: string
       *   amount?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     userName: string
       *     email?: string | null
       *     name?: string
       *     avatarUrl?: string
       *     phoneNumber?: string | null
       *     description?: string
       *     rights?: string
       *     // [items] start
       *     // [items] end
       *     rightsList?: string[]
       *     signature?: string
       *     enabled?: boolean
       *     date?: string
       *     id?: string | null
       *     normalizedUserName?: string | null
       *     normalizedEmail?: string | null
       *     emailConfirmed?: boolean
       *     passwordHash?: string | null
       *     securityStamp?: string | null
       *     concurrencyStamp?: string | null
       *     phoneNumberConfirmed?: boolean
       *     twoFactorEnabled?: boolean
       *     lockoutEnd?: string | null
       *     lockoutEnabled?: boolean
       *     accessFailedCount?: number
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      post_api_weixin_wx_pay_extract<
        Config extends Alova2MethodConfig<ApiResultOfApplicationUser> & {
          params: {
            id?: string;
            userTrueName?: string;
            amount?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfApplicationUser, 'general.post_api_weixin_wx_pay_extract', Config>;
      /**
       * ---
       *
       * [GET] 获取微信粉丝列表
       *
       * **path:** /api/Weixin/WxUsers/List
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   type?: string
       *   subscribe?: string
       *   startdate?: string
       *   enddate?: string
       *   keyword?: string
       *   page?: number
       *   pagesize?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     // [items] start
       *     // [items] end
       *     list?: Array<{
       *       openId: string
       *       unionId?: string
       *       nickName: string
       *       avatarUrl?: string
       *       sex?: number
       *       country?: string
       *       province?: string
       *       city?: string
       *       phoneNumber?: string
       *       identityNumber?: string
       *       description?: string
       *       isSubscribe?: boolean
       *       type?: number
       *       creationDate?: string
       *       lastActiveDate?: string
       *     }>
       *     page?: number
       *     pageSize?: number
       *     totalPageCount?: number
       *     totalItemCount?: number
       *     extendData?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_weixin_wx_users_list<
        Config extends Alova2MethodConfig<ApiResultOfPageListOfWxUser> & {
          params: {
            type?: string;
            subscribe?: string;
            startdate?: string;
            enddate?: string;
            keyword?: string;
            page?: number;
            pagesize?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfPageListOfWxUser, 'general.get_api_weixin_wx_users_list', Config>;
      /**
       * ---
       *
       * [GET] 通过openid获取微信粉丝
       *
       * **path:** /api/Weixin/WxUsers/get
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   openid?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     openId: string
       *     unionId?: string
       *     nickName: string
       *     avatarUrl?: string
       *     sex?: number
       *     country?: string
       *     province?: string
       *     city?: string
       *     phoneNumber?: string
       *     identityNumber?: string
       *     description?: string
       *     isSubscribe?: boolean
       *     type?: number
       *     creationDate?: string
       *     lastActiveDate?: string
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_weixin_wx_users_get<
        Config extends Alova2MethodConfig<ApiResultOfWxUser> & {
          params: {
            openid?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfWxUser, 'general.get_api_weixin_wx_users_get', Config>;
      /**
       * ---
       *
       * [POST] 创建微信粉丝
       *
       * **path:** /api/Weixin/WxUsers/Create
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   openId: string
       *   unionId?: string
       *   nickName: string
       *   avatarUrl?: string
       *   sex?: number
       *   country?: string
       *   province?: string
       *   city?: string
       *   phoneNumber?: string
       *   identityNumber?: string
       *   description?: string
       *   isSubscribe?: boolean
       *   type?: number
       *   creationDate?: string
       *   lastActiveDate?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     openId: string
       *     unionId?: string
       *     nickName: string
       *     avatarUrl?: string
       *     sex?: number
       *     country?: string
       *     province?: string
       *     city?: string
       *     phoneNumber?: string
       *     identityNumber?: string
       *     description?: string
       *     isSubscribe?: boolean
       *     type?: number
       *     creationDate?: string
       *     lastActiveDate?: string
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      post_api_weixin_wx_users_create<
        Config extends Alova2MethodConfig<ApiResultOfWxUser> & {
          data: WxUser;
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfWxUser, 'general.post_api_weixin_wx_users_create', Config>;
      /**
       * ---
       *
       * [PUT] 更新微信粉丝资料
       *
       * **path:** /api/Weixin/WxUsers/Update
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   openId: string
       *   unionId?: string
       *   nickName: string
       *   avatarUrl?: string
       *   sex?: number
       *   country?: string
       *   province?: string
       *   city?: string
       *   phoneNumber?: string
       *   identityNumber?: string
       *   description?: string
       *   isSubscribe?: boolean
       *   type?: number
       *   creationDate?: string
       *   lastActiveDate?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     openId: string
       *     unionId?: string
       *     nickName: string
       *     avatarUrl?: string
       *     sex?: number
       *     country?: string
       *     province?: string
       *     city?: string
       *     phoneNumber?: string
       *     identityNumber?: string
       *     description?: string
       *     isSubscribe?: boolean
       *     type?: number
       *     creationDate?: string
       *     lastActiveDate?: string
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      put_api_weixin_wx_users_update<
        Config extends Alova2MethodConfig<ApiResultOfWxUser> & {
          data: WxUser;
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfWxUser, 'general.put_api_weixin_wx_users_update', Config>;
      /**
       * ---
       *
       * [DELETE] 删除微信粉丝
       *
       * **path:** /api/Weixin/WxUsers/Delete
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   id?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     openId: string
       *     unionId?: string
       *     nickName: string
       *     avatarUrl?: string
       *     sex?: number
       *     country?: string
       *     province?: string
       *     city?: string
       *     phoneNumber?: string
       *     identityNumber?: string
       *     description?: string
       *     isSubscribe?: boolean
       *     type?: number
       *     creationDate?: string
       *     lastActiveDate?: string
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      delete_api_weixin_wx_users_delete<
        Config extends Alova2MethodConfig<ApiResultOfWxUser> & {
          params: {
            id?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfWxUser, 'general.delete_api_weixin_wx_users_delete', Config>;
      /**
       * ---
       *
       * [POST] 同步微信粉丝
       *
       * **path:** /api/Weixin/WxUsers/sync
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   nextOpenid?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     totalCount?: number
       *     count?: number
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      post_api_weixin_wx_users_sync<
        Config extends Alova2MethodConfig<ApiResultOfSyncApiResult> & {
          params: {
            nextOpenid?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfSyncApiResult, 'general.post_api_weixin_wx_users_sync', Config>;
    };
  }

  var WebApi_Weixin: WebApi_Weixin;
}
