/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/about/index" |
  "/pages/article/detail" |
  "/pages/article/list" |
  "/pages/ci/index" |
  "/pages/create-uni/index" |
  "/pages/demo/index" |
  "/pages/feedback/index" |
  "/pages/icon/index" |
  "/pages/login/index" |
  "/pages/login/privacyPolicy" |
  "/pages/login/register" |
  "/pages/login/userAgreement" |
  "/pages/my/index" |
  "/pages/pinia/index" |
  "/pages/request/index" |
  "/pages/router/demo-aftereach" |
  "/pages/router/demo-guard" |
  "/pages/router/demo-object" |
  "/pages/router/demo-params" |
  "/pages/router/demo-protected" |
  "/pages/router/demo-query" |
  "/pages/router/demo-string" |
  "/pages/router/index" |
  "/pages/uni-ku-root/index" |
  "/pages/user/changePassword" |
  "/pages/user/profile" |
  "/pages/user/settings" |
  "/pages/business/order/index" |
  "/pages/business/team/index" |
  "/pages/business/team/join" |
  "/subPages/styles/index" |
  "/subEcharts/echarts/index" |
  "/subAsyncEcharts/asyncEcharts/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/demo/index" | "/pages/my/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
