/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 后羿 接口文档 | App 模块 - version v9.0.9.0
 *
 * 后羿 项目接口文档, Powered By .NET 9.0.10
 *
 * OpenAPI version: 3.0.1
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'app.get_api_app_app_versions_check': ['GET', '/api/App/AppVersions/check'],
  'app.get_api_app_app_versions_get': ['GET', '/api/App/AppVersions/get'],
  'app.get_api_app_app_versions_download_last_apk': ['GET', '/api/App/AppVersions/download/last.apk'],
  'app.get_api_app_app_versions_list': ['GET', '/api/App/AppVersions/list'],
  'app.post_api_app_app_versions_create': ['POST', '/api/App/AppVersions/create'],
  'app.put_api_app_app_versions_update': ['PUT', '/api/App/AppVersions/update'],
  'app.delete_api_app_app_versions_delete': ['DELETE', '/api/App/AppVersions/delete'],
  'app.delete_api_app_app_versions_deletes': ['DELETE', '/api/App/AppVersions/deletes']
};
