/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 后羿 接口文档 | App 模块 - version v9.0.9.0
 *
 * 后羿 项目接口文档, Powered By .NET 9.0.10
 *
 * OpenAPI version: 3.0.1
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'app.CheckAppVersion': ['GET', '/api/App/AppVersions/check'],
  'app.GetAppVersion': ['GET', '/api/App/AppVersions/get'],
  'app.DownloadLastAppVersion': ['GET', '/api/App/AppVersions/download/last.apk'],
  'app.GetAppVersionList': ['GET', '/api/App/AppVersions/list'],
  'app.CreateAppVersion': ['POST', '/api/App/AppVersions/create'],
  'app.UpdateAppVersion': ['PUT', '/api/App/AppVersions/update'],
  'app.DeleteAppVersion': ['DELETE', '/api/App/AppVersions/delete'],
  'app.DeleteAppVersions': ['DELETE', '/api/App/AppVersions/deletes']
};
