/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * TNT.WebApi 接口文档 | App 模块 - version v9.0.11.0
 *
 * TNT.WebApi 项目接口文档, Powered By .NET 9.0.11
 *
 * OpenAPI version: 3.0.1
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'appVersion.checkAppVersion': ['GET', '/api/App/AppVersions/check'],
  'appVersion.getAppVersion': ['GET', '/api/App/AppVersions/get'],
  'appVersion.downloadAppVersion': ['GET', '/api/App/AppVersions/download/last.apk'],
  'appVersion.getAppVersionList': ['GET', '/api/App/AppVersions/list'],
  'appVersion.createAppVersion': ['POST', '/api/App/AppVersions/create'],
  'appVersion.updateAppVersion': ['PUT', '/api/App/AppVersions/update'],
  'appVersion.deleteAppVersion': ['DELETE', '/api/App/AppVersions/delete'],
  'appVersion.deleteAppVersions': ['DELETE', '/api/App/AppVersions/deletes']
};
