/* eslint-disable */
/* biome-ignore-all */
/* stylelint-disable */
/* editorconfig-checker-disable-file */
/* oxlint-disable */
/* oxcformat-ignore */
/**
 * TNT.WebApi 接口文档 | App 模块 - version v10.0.9.0
 *
 * TNT.WebApi 项目接口文档, Powered By .NET 10.0.12
 *
 * OpenAPI version: 3.1.1
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://worma.js.org
 *
 * **Do not edit the file manually.**
 */
import type { Alova, MethodType, AlovaGenerics, AlovaMethodCreateConfig } from 'alova';
import { Method } from 'alova';
import apiDefinitions from './apiDefinitions';

const cache = Object.create(null);
const createFunctionalProxy = (array: (string | symbol)[], alovaInstance: Alova<AlovaGenerics>, configMap: any) => {
  const apiPathKey = array.join('.') as keyof typeof apiDefinitions;
  if (cache[apiPathKey]) {
    return cache[apiPathKey];
  }
  const proxy = new Proxy(function () {}, {
    get(_, property) {
      const newArray = [...array, property];
      return createFunctionalProxy(newArray, alovaInstance, configMap);
    },
    apply(_, __, [config]) {
      const apiItem = apiDefinitions[apiPathKey];
      if (!apiItem) {
        throw new Error(`the api path of \`${apiPathKey}\` is not found`);
      }
      const mergedConfig = {
        ...configMap[apiPathKey],
        ...config
      };
      const [method, url] = apiItem;
      const pathParams = mergedConfig.pathParams;
      const urlReplaced = url!.replace(/\{([^}]+)\}/g, (_, key) => {
        const pathParam = pathParams[key];
        return pathParam;
      });
      delete mergedConfig.pathParams;
      let data = mergedConfig.data;
      if (Object.prototype.toString.call(data) === '[object Object]' && typeof FormData !== 'undefined') {
        let hasBlobData = false;
        const formData = new FormData();
        for (const key in data) {
          if (Array.isArray(data[key])) {
            for (const ele of data[key]) {
              formData.append(key, ele);
              if (ele instanceof Blob) {
                hasBlobData = true;
              }
            }
          } else {
            formData.append(key, data[key]);
            if (data[key] instanceof Blob) {
              hasBlobData = true;
            }
          }
        }
        data = hasBlobData ? formData : data;
      }
      return new Method(method!.toUpperCase() as MethodType, alovaInstance, urlReplaced, mergedConfig, data);
    }
  });
  cache[apiPathKey] = proxy;
  return proxy;
};

export const createApis = (alovaInstance: Alova<AlovaGenerics>, configMap: any) => {
  const Apis = new Proxy({} as Webapi_App, {
    get(_, property) {
      return createFunctionalProxy([property], alovaInstance, configMap);
    }
  });
  return Apis;
};

export const mountApis = (Apis: Webapi_App) => {
  (globalThis as any).Webapi_App = Apis;
};

type MethodConfig<T> = AlovaMethodCreateConfig<
  (typeof import('./index'))['alovaInstance'] extends Alova<infer AG> ? AG : any,
  any,
  T
>;
type APISofParameters<Tag extends string, Url extends string> = Tag extends keyof Webapi_App
  ? Url extends keyof Webapi_App[Tag]
    ? Webapi_App[Tag][Url] extends (...args: any) => any
      ? Parameters<Webapi_App[Tag][Url]>
      : any
    : any
  : any;
type MethodsConfigMap = {
  [P in keyof typeof import('./apiDefinitions').default]?: MethodConfig<
    P extends `${infer Tag}.${infer Url}` ? Parameters<NonNullable<APISofParameters<Tag, Url>[0]>['transform']>[0] : any
  >;
};
export const withConfigType = <Config extends MethodsConfigMap>(config: Config) => config;
