/* tslint:disable */
/* eslint-disable */
/**
 * 后羿 接口文档 | App 模块 - version v9.0.9.0
 *
 * 后羿 项目接口文档, Powered By .NET 9.0.10
 *
 * OpenAPI version: 3.0.1
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from './index';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export interface AppVersion2 {
  id?: string;
  appId: string;
  version: string;
  versionValue: number;
  androidFileUrl?: string;
  iosFileUrl?: string;
  description?: string;
  enabled?: boolean;
  date?: string;
}
export type AppVersion = {
  id?: string;
  appId: string;
  version: string;
  versionValue: number;
  androidFileUrl?: string;
  iosFileUrl?: string;
  description?: string;
  enabled?: boolean;
  date?: string;
} | null;
export interface ApiResultOfAppVersion {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: AppVersion;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export type PageListOfAppVersion = {
  list?: AppVersion2[];
  page?: number;
  pageSize?: number;
  totalPageCount?: number;
  totalItemCount?: number;
  extendData?: null;
} | null;
export interface ApiResultOfPageListOfAppVersion {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: PageListOfAppVersion;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
export interface ApiResultOfint {
  /**
   * 响应编号
   */
  code?: number;
  /**
   * 响应消息
   */
  message?: string;
  /**
   * 响应数据 T
   */
  data?: number;
  /**
   * 扩展数据
   */
  extend?: null;
  /**
   * 请求是否返回正确
   */
  isSuccess?: boolean;
}
declare global {
  interface Webapi_App {
    app: {
      /**
       * ---
       *
       * [GET] 检测app版本信息
       *
       * **path:** /api/App/AppVersions/check
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   appid?: string
       *   version?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     id?: string
       *     appId: string
       *     version: string
       *     versionValue: number
       *     androidFileUrl?: string
       *     iosFileUrl?: string
       *     description?: string
       *     enabled?: boolean
       *     date?: string
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_app_app_versions_check<
        Config extends Alova2MethodConfig<ApiResultOfAppVersion> & {
          params: {
            appid?: string;
            version?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfAppVersion, 'app.get_api_app_app_versions_check', Config>;
      /**
       * ---
       *
       * [GET] 查询app版本详情
       *
       * **path:** /api/App/AppVersions/get
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   id?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     id?: string
       *     appId: string
       *     version: string
       *     versionValue: number
       *     androidFileUrl?: string
       *     iosFileUrl?: string
       *     description?: string
       *     enabled?: boolean
       *     date?: string
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_app_app_versions_get<
        Config extends Alova2MethodConfig<ApiResultOfAppVersion> & {
          params: {
            id?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfAppVersion, 'app.get_api_app_app_versions_get', Config>;
      /**
       * ---
       *
       * [GET] 下载app最新版本
       *
       * **path:** /api/App/AppVersions/download/last.apk
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      get_api_app_app_versions_download_last_apk<Config extends Alova2MethodConfig<null>>(
        config?: Config
      ): Alova2Method<null, 'app.get_api_app_app_versions_download_last_apk', Config>;
      /**
       * ---
       *
       * [GET] 获取app版本列表
       *
       * **path:** /api/App/AppVersions/list
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   enabled?: boolean
       *   keyword?: string
       *   page?: number
       *   pagesize?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     // [items] start
       *     // [items] end
       *     list?: Array<{
       *       id?: string
       *       appId: string
       *       version: string
       *       versionValue: number
       *       androidFileUrl?: string
       *       iosFileUrl?: string
       *       description?: string
       *       enabled?: boolean
       *       date?: string
       *     }>
       *     page?: number
       *     pageSize?: number
       *     totalPageCount?: number
       *     totalItemCount?: number
       *     extendData?: null
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      get_api_app_app_versions_list<
        Config extends Alova2MethodConfig<ApiResultOfPageListOfAppVersion> & {
          params: {
            enabled?: boolean;
            keyword?: string;
            page?: number;
            pagesize?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfPageListOfAppVersion, 'app.get_api_app_app_versions_list', Config>;
      /**
       * ---
       *
       * [POST] 发布app版本
       *
       * **path:** /api/App/AppVersions/create
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   id?: string
       *   appId: string
       *   version: string
       *   versionValue: number
       *   androidFileUrl?: string
       *   iosFileUrl?: string
       *   description?: string
       *   enabled?: boolean
       *   date?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     id?: string
       *     appId: string
       *     version: string
       *     versionValue: number
       *     androidFileUrl?: string
       *     iosFileUrl?: string
       *     description?: string
       *     enabled?: boolean
       *     date?: string
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      post_api_app_app_versions_create<
        Config extends Alova2MethodConfig<ApiResultOfAppVersion> & {
          data: AppVersion2;
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfAppVersion, 'app.post_api_app_app_versions_create', Config>;
      /**
       * ---
       *
       * [PUT] 更新app版本
       *
       * **path:** /api/App/AppVersions/update
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   id?: string
       *   appId: string
       *   version: string
       *   versionValue: number
       *   androidFileUrl?: string
       *   iosFileUrl?: string
       *   description?: string
       *   enabled?: boolean
       *   date?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     id?: string
       *     appId: string
       *     version: string
       *     versionValue: number
       *     androidFileUrl?: string
       *     iosFileUrl?: string
       *     description?: string
       *     enabled?: boolean
       *     date?: string
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      put_api_app_app_versions_update<
        Config extends Alova2MethodConfig<ApiResultOfAppVersion> & {
          data: AppVersion2;
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfAppVersion, 'app.put_api_app_app_versions_update', Config>;
      /**
       * ---
       *
       * [DELETE] 删除指定项
       *
       * **path:** /api/App/AppVersions/delete
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   id?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: {
       *     id?: string
       *     appId: string
       *     version: string
       *     versionValue: number
       *     androidFileUrl?: string
       *     iosFileUrl?: string
       *     description?: string
       *     enabled?: boolean
       *     date?: string
       *   } | null
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      delete_api_app_app_versions_delete<
        Config extends Alova2MethodConfig<ApiResultOfAppVersion> & {
          params: {
            id?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfAppVersion, 'app.delete_api_app_app_versions_delete', Config>;
      /**
       * ---
       *
       * [DELETE] 批量删除指定项
       *
       * **path:** /api/App/AppVersions/deletes
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = string[]
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应编号
       *   code?: number
       *   // 响应消息
       *   message?: string
       *   // 响应数据 T
       *   data?: number
       *   // 扩展数据
       *   extend?: null
       *   // 请求是否返回正确
       *   isSuccess?: boolean
       * }
       * ```
       */
      delete_api_app_app_versions_deletes<
        Config extends Alova2MethodConfig<ApiResultOfint> & {
          data: string[];
        }
      >(
        config: Config
      ): Alova2Method<ApiResultOfint, 'app.delete_api_app_app_versions_deletes', Config>;
    };
  }

  var Webapi_App: Webapi_App;
}
